### PR TITLE
Revert ADSB and Sentinel fonts

### PR DESCRIPTION
**Pull request by DzikuVx**
As reported by @Jetrell in #1244 , fonts from #1244 are broken and miss some characters in some cases.

@ShikOfTheRa FYI, @Jetrell says that the glyphs for Sentinel and ADSB will be added in a correct way in a week or so.

### CODE REVIEW

**Comment by Jetrell** [comment]
@ShikOfTheRa For a bit more information. I'm doing a cleanup of the older fonts. So the ADSB glyphs will be added with this cleanup.
Thanks

**Comment by ShikOfTheRa** [comment]
@jetrell - thank buddy! Not sure what I did there. I ran the script and tested the default which seemed to look OK. I'll have to look back to learn...  142/143 are for  antenna tracking/video telemetry and 253 for the  ADSB which I hope to update this week following a test flight.

**Comment by Jetrell** [comment]
@ShikOfTheRa I think what might of happened. Was you updated your addition to the .png files. Then converted them to .mcm files.
Problem with this is... At present the older .png files are incomplete.
This is what I'm working on. Once i'm finished re-drawing, re-shading and bringing up the old fonts to a cleaner standard. I will load them all.
You don't have to worry about adding 142/143 and 253.  I will also add them to the cleanup. My reason being... I will also change the stature and alignment of 253 to suit each specific font style.

I should have them finished later this week.

**Comment by ShikOfTheRa** [comment]
Ah OK, I get it. Thanks for the update and the effort to clean up

**Comment by Jetrell** [comment]
@ShikOfTheRa Would you be interested in telling me what you think of the modified Default font.
Smaller descriptive characters, less dark heavy shading, but more selective shading. And better vertical alignment of the alphanumeric and descriptive characters.

Many people use Default font and I don't want to put it though without an opinion?

[Default_mod.zip](https://github.com/iNavFlight/inav-configurator/files/6411308/Default_mod.zip)

**Comment by ShikOfTheRa** [comment]
Yes - I will check today. I could not install fonts and was just about to raise issue and see fix from Pawel. will be end of day as have to work.. :(

**Comment by ShikOfTheRa** [comment]
@Jetrell 

Whatever changes you make, you can be sure you’ll not please everyone. It’s an impossible task with a lot of personal preference. :)

Most of the changes are small and subtle – probably many will not notice
Changes look Ok to me in the goggles. I prefer the new look alt/azi/air  
I do prefer the original style batt icon (sorry!)

One from before that has always triggered my OCD – 0xA/B – I have efficiency lined up on my display and this one just looks odd. Also 0x9D/E. Not sure if possible to resolve in a nice way.

**Comment by Jetrell** [comment]
@ShikOfTheRa Thanks for your response. When you say battery. I assume you mean the larger battery icon for a while back? 
I didn't change it. Someone else already got there first. 

`0xab` WH. That easy to put back to the way it was.

`0x9d/e `(mAh/km) has been shifted to the left, being a double character. To suit a future PR 0x08 (Ah/km) single character.
 I was trying to keep them in the same area for the units change over at 1k.

Send me a picture of your screen layout. It may help me work out something to your taste.

Like you said.. Its a personal preference thing. I have been entertaining doing this for a while. And I keep my ears open to peoples likes and dislike of particular font types.
Surprisingly, I've modified/altered up to 80% of `Large` and `Bold`. I personally never used them. But IMO, they look heaps tidier. Before they where just a mush of additions that never suited the font type.

**Comment by ShikOfTheRa** [comment]
Hi @Jetrell sorry for delay - been tied up with the adsb code and some flight tetsting.

voltage font - cool

0xAB:
My bad – I meant 0x0A/B instead of 0xAB
It is just using 2 chars instead of one. Its really minor. It looks a little odd in stack like image. :
image

0x9d/e - OK - cool. 

I've submitted the adsb PR - so would be great to add the 0xFD font. Feel free to amend how you like!

And I also just noticed 0x8E/F
These need to be full width characters to allow a groundstation to have better chance of capturing data sent using video telemetry.
It is on the very first line which is not normally visible in goggles or most video recordings

**Comment by Jetrell** [comment]
@ShikOfTheRa Here are all the new .png folders with modified (0x8E/F). as you described. I don't know they were specifically responsible for the GS data capture.

If you want to merge them all yourself now, please let me know **soon** ?

[new iNav .png OSD font folders.zip](https://github.com/iNavFlight/inav-configurator/files/6433393/new.iNav.png.OSD.font.folders.zip)

**Comment by ShikOfTheRa** [comment]
@Jetrell they look ok to me - you should merge as deserve the credit! Looks good.

**Comment by Jetrell** [comment]
> 
> 
> @Jetrell they look ok to me - you should merge as deserve the credit! Looks good.

I'm not concerned about credit. If you want to do a PR now. Go right ahead, so it can be used :+1:

**Comment by ShikOfTheRa** [comment]
I am struggling with the max7456tool to "generate" mcm

**Comment by Jetrell** [comment]
> 
> 
> I am struggling with the max7456tool to "generate" mcm

@shellixyz updated them today.

**Comment by ShikOfTheRa** [comment]
Awesome. Thanks for your work. 

Not sure what is stopping mine from working. Cannot find the cause. Weird as it did run the other day

**Pull request merged**
