### PR TITLE
OSD Tab Updates for HDZero and DJI Support

### PR DESCRIPTION
**Pull request by geoffsim**
- Replace Video Format box with an HDZero box when HDZero enabled in ports tab.
- Hide DJI references when not enabled in ports tab, or HDZero enabled in ports tab.
- Create a button in HDZero box to show / hide guides.
- Add help information to the box to explain the guides.
- Add new SD mode guides when HDZero is enabled in the ports tab.

### CODE REVIEW

**Comment by jeffhendrix** [comment]
@geoffsim, I have made some changes to inav-configurator and several of them overlap with yours.
My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.
Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.
Would you like me to integrate your changes into mine?

**Comment by geoffsim** [comment]
Good morning, Jeff. Sure, help yourself. Sent from my phoneOn 3 Oct 2022, at 00:36, Jeff Hendrix ***@***.***> wrote:﻿
@geoffsim, I have made some changes to inav-configurator and several of them overlap with yours.
My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.
Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.
Would you like me to integrate your changes into mine?

**Comment by geoffsim** [comment]
Hi. I see you have merged my changes. Are these in the master branch yet?Also, did you make any changes to my inav branch too? Regards,Geoff. Sent from Mail for Windows From: Jeff HendrixSent: 03 October 2022 00:36To: iNavFlight/inav-configuratorCc: Geoff Sim; MentionSubject: Re: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR ***@***.***, I have made some changes to inav-configurator and several of them overlap with yours.My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.Would you like me to integrate your changes into mine?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by geoffsim** [comment]
Further to my last email, it looks like my PR is redundant ? Sent from Mail for Windows From: GeoffSent: 18 October 2022 07:29To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Hi. I see you have merged my changes. Are these in the master branch yet?Also, did you make any changes to my inav branch too? Regards,Geoff. Sent from Mail for Windows From: Jeff HendrixSent: 03 October 2022 00:36To: iNavFlight/inav-configuratorCc: Geoff Sim; MentionSubject: Re: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR ***@***.***, I have made some changes to inav-configurator and several of them overlap with yours.My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.Would you like me to integrate your changes into mine?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by geoffsim** [comment]
Merged with another branch

**Comment by geoffsim** [comment]
Never mind 😊I see it is all done and merged  – I have deleted my PR and am testing the master branches of inav and config now... Cheers,Geoff. From: GeoffSent: 18 October 2022 08:20To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Further to my last email, it looks like my PR is redundant ? Sent from Mail for Windows From: GeoffSent: 18 October 2022 07:29To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Hi. I see you have merged my changes. Are these in the master branch yet?Also, did you make any changes to my inav branch too? Regards,Geoff. Sent from Mail for Windows From: Jeff HendrixSent: 03 October 2022 00:36To: iNavFlight/inav-configuratorCc: Geoff Sim; MentionSubject: Re: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR ***@***.***, I have made some changes to inav-configurator and several of them overlap with yours.My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.Would you like me to integrate your changes into mine?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by geoffsim** [comment]
Testing of HDZero modes has shown that something has been broken in the mode setting on the firmware. I will have to investigate ☹ Sent from Mail for Windows From: GeoffSent: 18 October 2022 09:50To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Never mind 😊I see it is all done and merged  – I have deleted my PR and am testing the master branches of inav and config now... Cheers,Geoff. From: GeoffSent: 18 October 2022 08:20To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Further to my last email, it looks like my PR is redundant ? Sent from Mail for Windows From: GeoffSent: 18 October 2022 07:29To: iNavFlight/inav-configurator; iNavFlight/inav-configuratorCc: MentionSubject: RE: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR #1589) Hi. I see you have merged my changes. Are these in the master branch yet?Also, did you make any changes to my inav branch too? Regards,Geoff. Sent from Mail for Windows From: Jeff HendrixSent: 03 October 2022 00:36To: iNavFlight/inav-configuratorCc: Geoff Sim; MentionSubject: Re: [iNavFlight/inav-configurator] OSD Tab Updates for HDZero and DJI Support (PR ***@***.***, I have made some changes to inav-configurator and several of them overlap with yours.My changes are to allow configuring DJI wtfos changes. I'm also hiding options based on the ports selection.Pawel has also made changes that remove the HDZero option from the ports tab and replace it with MSP Displayport which will run both HDZero and DJI wtfos.Would you like me to integrate your changes into mine?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Pull request closed without merging**
