### PR TITLE
Add Crossfire elements to OSD

### PR DESCRIPTION
**Pull request by expipiplus1**
see https://github.com/iNavFlight/inav/pull/4517

### CODE REVIEW

**Comment by Jetrell** [comment]
@expipiplus1  These might come in handy when this PR gets merged.
 The standard RSSI symbol should be good for the rest.

Down Link Quality
Downlink Quality
Up Link Quality
Uplink Quality
Received Frequency Mode
RFMD
Signal to Noise Ratio
SNR
Down Link Power
Downlink Power
Up Link Power
Uplink Power


[CRSF link.png.zip](https://github.com/iNavFlight/inav-configurator/files/3908039/CRSF.link.png.zip)

**Comment by expipiplus1** [comment]
Thanks, they look great, @Jetrell

**Comment by OptimusTi** [comment]
Hello @expipiplus1 

Looks like were interested in the same Crossfire info for the OSD! I contacted atomiclama from iNavFlight/inav#5089 and added some mods to his code. Looks like he's not interested and passed the baton. 

I have the code working on Inav 2.5.2 and mimicking the functions of the TBS Core, EVO and FPVision OSD. The OSD shows the data points coming from Crossfire needed during flight.

* RxSNR (As an alarm, in dB.  This number only pops up when the ratio is close to 0dB)
* RSS1 & RSSI2 (in -dBm) with diversity symbols
* RF Profile Mode and LQ% e.g. 2:100% like represented in Betaflight.
* TX Power in mW.
* I have a couple of fonts with characters for RSSI2, dB, dBm, mW, and SNR.

This video shows the OSD working. Some Crossfire users are testing 2.5.2 right now. 

Record_2020_08_16_22_16_21_109

This image has the OSD menu in the elements menu. The CRSF RX menu has the SRN alarm level and elements.

pic6

**Comment by expipiplus1** [comment]
It would be great to get this into inav. Given recent interest I'd be happy to do the final touches on my original PR, although I wouldn't be able to test it myself. Also happy for the new PR to be merged.

**Comment by OptimusTi** [comment]
Cool.

There's no new PR for the Inav part. The features above are modifications I made to atomiclama's code.

Looks like Pawel wants everything ready for testing with the community. We'll need to finish the configurator code and fonts.

**Comment by DzikuVx** [comment]
@OptimusTi yes, we need it as a package with all the required functions. I'm however putting this PR in plan for 2.6

**Comment by DzikuVx** [comment]
Replaced by #1056 
thanks for the effort!

**Pull request closed without merging**
