### PR TITLE
OpenLayers and OpenStreetMap instead of Google Maps

### PR DESCRIPTION
**Pull request by DzikuVx**
@digitalentity you might want to check and deploy as soon as possible.
Today we exceeded the quote on GM and it was required to clean it up.
So.... OpenStreetMap, here we come... Rest of planned changes will come later

### CODE REVIEW

**Comment by stronnag** [comment]
You appear to have lat,lon the wrong way around. I am NOT in the Indian Ocean!
screenshot-20170304215940-1253x500

**Comment by stronnag** [comment]
Confirmed, tested 'live'. Looks great.

**Comment by digitalentity** [comment]
Tested, works:
image

**Comment by DzikuVx** [comment]
In that case merging back

**Pull request merged**
