### PR TITLE
adding Ukrainian translations from crowdin

### PR DESCRIPTION
**Pull request by smsnvc**
Adding recent translations of configurator to Ukrainian.
Hope it will become a part of version 8.

### CODE REVIEW

**Comment by smsnvc** [comment]
@bfmvsa , hope you had a look on crowdin while it was in progress.

**Comment by bfmvsa** [comment]
@smsnvc thank you for your contributions! 
As a native speaker, I can confirm that this PR looks good for me.

**Comment by smsnvc** [comment]
Hi @sensei-hacker ,

you were the reviewer of the Ukrainian in September.
https://github.com/iNavFlight/inav-configurator/pull/2196

This PR improves some of the previous translations and adds translations for strings added between Sep and Nov. 
As for me, it makes sense to include this batch of strings into 8 milestone.

**Comment by MrD-RC** [comment]
Thanks for this update. There shouldn't be any more strings added to Configurator for 8.0.0.

**Pull request merged**
