### PR TITLE
dont init switchery for non checkbox inputs

### PR DESCRIPTION
**Pull request by error414**
it's fix for issue https://github.com/iNavFlight/inav-configurator/issues/2208

### CODE REVIEW

**Comment by MrD-RC** [comment]
Works fine. Just need the mac errors resolved before merging.

**Comment by error414** [comment]
I would say that osx build more times does not work than works. If you look at error, it's probably not caused by my changes.

**Comment by error414** [comment]
ok, fixed :), I did not change anything and it passed :D

**Comment by MrD-RC** [comment]
It can be a pain in the ass. I re-ran it too. Just in case it was a glitch. Bloody macs.

**Pull request merged**
