### PR TITLE
Adding Ukrainian translation for the INAV Configurator

### PR DESCRIPTION
**Pull request by smsnvc**
The idea of translation was discussed with @sensei-hacker, who said that it's possible in general in June 2024. 

If you want to review, suggest some change or fix errors - please use crowdin to send your suggestions, because it is a source and an instrument for translations. Modifying in different places will make it more difficult to merge 
https://crowdin.com/project/inav-in-ukrainian

I've tried to review and use some of the good suggestions [AndrewKZV](https://github.com/AndrewKZV) introduced in their translation: https://github.com/iNavFlight/inav/discussions/10283

### CODE REVIEW

**Comment by MrD-RC** [comment]
дякую

**Comment by sensei-hacker** [comment]
The one thing I know how to check looks good -
The words "English" and "Deutsch" are not translated, so that's good.

Those top lines should also be updated in the English file, so that when it's in English it knows how to display the option to switch.

**Comment by smsnvc** [comment]
@sensei-hacker , thanks. I've updated the English one as well.
@MrD-RC , thanks, will pass to volunteers who worked with me on the translation.

**Comment by MrD-RC** [comment]
@smsnvc no need to thank me. You guys have put in all the work. It's always great to see another language supported. The only issue is when new things get added, the translations are also needed. Personally, my Ukrainian is about 10-15 words. So I would be pretty useless at this stage 🤣

Thanks guys, we really appreciate it.

**Comment by smsnvc** [comment]
@MrD-RC , in such threads there is usually a lot for what a person can say thanks. For comments that make us feel not so stranded or for your work on INAV or for your helpful videos.

We've managed to keep translations of ESC, ELRS, and Betaflight configurators in sync with the code base. So hopefully INAV will join the family. And there will be more work for the developers since not all strings are translatable. For instance, in the OSD setup.

**Comment by bfmvsa** [comment]
A few comments regarding this PR and i18n in general:

1. Looks like we don't support Cyrillic bold text (see screenshot). In my `new-ui` branch it is already fixed btw (see screenshot)
2. Text in the sensors bar is need to be fixed or we should use text-overflow: ellipsis; as on the screenshot.
3. Some minor fixes are needed, for example in my opinion we do not need to translate PID abbr like we do it for GPS (I'll contribute it in CrowdIn)

screenshot 2024-09-22 at 11 03 44
screenshot 2024-09-22 at 11 07 24
screenshot 2024-09-22 at 11 11 06
screenshot 2024-09-22 at 11 17 38
screenshot 2024-09-22 at 11 20 02
screenshot 2024-09-22 at 11 23 49

**Comment by bfmvsa** [comment]
Here are some screenshots from ui I am working on (also need some small fixes)
screenshot 2024-09-22 at 11 30 04
screenshot 2024-09-22 at 11 33 56

**Comment by smsnvc** [comment]
> 1. Looks like we don't support Cyrillic bold text (see screenshot). In my `new-ui` branch it is already fixed btw (see screenshot)
> 2. Text in the sensors bar is need to be fixed or we should use text-overflow: ellipsis; as on the screenshot.

Thanks for addressing it, looks cool.

> 3. Some minor fixes are needed, for example in my opinion we do not need to translate PID abbr like we do it for GPS (I'll contribute it in CrowdIn)

There is usually a question to what degree to translate, to what extend. PID vs CLI vs GPS etc. There are some rules, for GPS is rarely translated (https://uk.wikipedia.org/wiki/GPS). Same as names of the technologies like DSHOT, SmartAudio or UART.

With PID it's a different story, becuase it's taught in schools and universities as cyrilic. And when you read it in the text, it's quite confusing to see latin P, which is written the same as Cyriliс Р. And if you use purely English language for everything in PID (including P-Term, Feedforward), we come to the situation when the users do not understand P-Term vs P (as a multiplier). Novice pilots can't translate the word term( because it has ~30 different translations). We had this constant struggle while translating the Betaflight, which had PID without translation initially. And at some point we understood that we should use Ukrainian variants to deliver consistent experiece.

Our task is to make the translation look familiar, accessible, encourages to read and learn, give "I can do it" attitude. I understand, that for those who are proficient in English, used English interface, it may look challenging. They may not see the benefits in using the translated interface. This is fine. Our target audience for the translated interface has challenges with English and would prefer to read explanations in their native language.

**Comment by bfmvsa** [comment]
@smsnvc Thanks. Now I see that your investigation into this topic was much deeper than mine so let's leave these things as it is, thank you.
From my side I will try to remove all hardcoded references from the project and move them into the messages.json file, so we will be able to translate it as well.

@MrD-RC @sensei-hacker FYI from my side as a native Ukrainian speaker everything looks good in this PR.

**Comment by MrD-RC** [comment]
> @MrD-RC @sensei-hacker FYI from my side as a native Ukrainian speaker everything looks good in this PR.

дуже добре

**Comment by sensei-hacker** [comment]
Based on the last two comments, it sounds like no further changes are needed?
Does anyone see anything that needs to be done, or is this ready to merge?

**Comment by bfmvsa** [comment]
@sensei-hacker Yes, everything looks good. Also, I just created a side PR with css fix for the sensors block: https://github.com/iNavFlight/inav-configurator/pull/2200

**Comment by smsnvc** [comment]
To me it looks good enough. 
Of course, there will be more work once new strings are added or issues spotted.

**Comment by MrD-RC** [comment]
@sensei-hacker it looks like @smsnvc is still pushing changes to the branch. 

@smsnvc and @bfmvsa let us know when you both believe this is ready.

**Comment by smsnvc** [comment]
@MrD-RC , sorry, decided to translate your latest strings in messages while it's not merged yet.
Now it should be fine to merge.

**Review by sensei-hacker — APPROVED** [review]

**Pull request merged**
