### PR TITLE
Osd custom

### PR DESCRIPTION
**Pull request by error414**
PR for inav, there is whole description:  https://github.com/iNavFlight/inav/pull/9508

### CODE REVIEW

**Comment by Jetrell** [comment]
@error414 Would you be willing to provide a build from your branch, so I can test it ? Thanks

**Comment by error414** [comment]
what target would you like? Compiling on WSL is so slow.

**Comment by Jetrell** [comment]
Windows 64.. Thankyou

**Comment by error414** [comment]
https://drive.google.com/drive/folders/1LbWuqTitFY0AOPa1aKKMw8DMFwGpx_UG?usp=sharing it's compiled from master, you need configurator + firmware for FC

**Pull request merged**
