### PR TITLE
Launch settings in Advanced tunning tab

### PR DESCRIPTION
**Pull request by pablitous**
It requieres an INAV update also. i will write link in the comments

### CODE REVIEW

**Comment by pablitous** [comment]
https://github.com/iNavFlight/inav/pull/5829

**Comment by fiam** [comment]
@pablitous We don't add new MSP message handlers for retrieving settings, the generic settings interface should be used instead. Check e.g. the OSD tab for an example https://github.com/iNavFlight/inav-configurator/blob/a178f0781fa5ea21eef37409d2b033891a6a6d6a/tabs/osd.html#L60 (the `<input>` elements with a `data-setting` attribute. Feel free to ask in the Telegram group if you need further guidance.

**Comment by pablitous** [comment]
thank you guys for the help, i already make it work without new msp messages. I did it just like osd tab

**Comment by pablitous** [comment]
https://github.com/iNavFlight/inav-configurator/pull/1020

**Pull request closed without merging**
