### PR TITLE
Separate D and CD/FF adjustments

### PR DESCRIPTION
**Pull request by avsaase**
This PR aligns the adjustment indices with https://github.com/iNavFlight/inav/pull/6674. Also reorders them in the dropdown menu.

### CODE REVIEW

**Comment by avsaase** [comment]
@DzikuVx don't forget this one, otherwise setting up the adjustments is a pain.

**Comment by rts18** [comment]
@avsaase This makes it heaps easier to tune :+1: 
Just a small bug I found on the OSD setup page. The Roll element is displayed for Pitch as well as Roll.  No big issue.


Capture

**Comment by avsaase** [comment]
Thanks, I missed that one. Fixed in PR ^^

**Comment by breadoven** [comment]
Some adjustments seem to be missing from the dropdown list in the 3.0 version at http://seyrsnys.myzen.co.uk/inav-configurator-next/, VTX power etc. Can set them in the CLI using adjrange but the dropdown list appears empty in configurator. Bug ?

**Comment by avsaase** [comment]
Ah yes, I forgot to change something. Fixed in #1225.

**Pull request merged**
