### PR TITLE
GUI rework

### PR DESCRIPTION
**Pull request by skaman82**
bildschirmfoto 2016-05-24 um 17 41 42

bildschirmfoto 2016-05-24 um 20 11 51

### CODE REVIEW

**Comment by skaman82** [comment]
I also noticed that there ist a "calibration" menu entry but the tab-files for that are missing... Is someone working on that?

**Comment by theArchLadder** [comment]
Wow, beautiful! :smiley: 

Is there any green left? For example, in the blackbox tab there is green when a button is pressed, and the progress bar for downloading the log is green.

Do you have an automated way to search and replace colors in all files? I could perhaps come up with something if you don't.

**Comment by DzikuVx** [comment]
Yay

**Comment by digitalentity** [comment]
@skaman82 cool, I absolutely like it! Please merge at will!

I've started working on Calibration tab, but apparently forgot to commit the new files. Unfortunately they are on my home PC which is inaccessible at the moment.

**Comment by skaman82** [comment]
The are some areas untested due to missing equipment:
• Onboard SD Card interface
• Race Transponder Tab

@theArchLadder I can't find where the green color is coming from in this dialog:
bildschirmfoto 2016-05-24 um 19 55 42. Everything else should be fine

**Comment by skaman82** [comment]
Merging now, will do a small follow-up in another PR, if necessary

**Comment by theArchLadder** [comment]
Just tried it, looks fantastic, amazing work! :+1:

**Pull request merged**
