### PR TITLE
[Electron] Fixes and Adjustments

### PR DESCRIPTION
**Pull request by Scavanger**
- MacOS:
   - Nice icon for DMG
   - Fix bug when Configurator was minimized and dock icon is clicked

- Fix (Workaround):  After a MessageBox (alert()) was displayed, all input fields stopped working.
- Fix Blackbox tab (save data flash)
- Removed useless MSC button in blackbox tab
- Adjust Readme
- Add context menu  (copy and paste, undo, redo)
- Fix LED Tab
- Fix Github Actions (What still worked yesterday. )

### CODE REVIEW

**Comment by Jetrell** [comment]
Thank you for the fixes @Scavanger 

I found another issues that I'm not sure if you're aware of. 
When attempting to load a previously saved mission file from a js build.. Or even save a mission file that has been made with the electron build.
This log error occurred. `error reading file (xml2js not found)`

**Comment by Scavanger** [comment]
> Thank you for the fixes @Scavanger
> 
> I found other issues that I'm not sure if you're aware of with the Windows build. When attempting to load a previously saved mission file from a js build.. Or even save a mission file that has been made with the electron build. This log error occurred. `error reading file (xml2js not found)`

Thanks for finding it. Fixed.

**Comment by mmosca** [comment]
Not exactly related, but is it possible to use https://github.com/electron/universal to distribute a single universal binary application, instead of separate x64 and arm64?

**Comment by Scavanger** [comment]
> Not exactly related, but is it possible to use https://github.com/electron/universal to distribute a single universal binary application, instead of separate x64 and arm64?

I have already tried this in the GitHub Actions, but unfortunately it always cancelled with the following error message:

```
✖ Stitching darwin/x64 and darwin/arm64 into a darwin/universal package [FAILED: While trying to merge mach-o files across your apps we found a mismatch, the number of mach-o files is not the same between the arm64 and x64 builds]
```

I'm not a Mac expert if you know how to fix the error, please feel free.

**Comment by DzikuVx** [comment]
let's merge and have incremental improvements

**Pull request merged**
