### PR TITLE
Arntlse safehome mp

### PR DESCRIPTION
**Pull request by ArnoTlse**
Hi, 

This is the new PR coming from a complete rework of previous PR #1173.

In this PR, there is : 

-  All waypoint type : JUMP, SET_HEAD, POI, RTH, WP, PH_TIME
-  Safe Home :  add Safe Home settings menu to manage and plot safe home point accessible through a similar button on the map as settings. : see related PR #1182 
-  WP insertion :  add ability to insert a waypoint in existing mission by clicking on the branch where user wants to insert new point

### CODE REVIEW

**Comment by ArnoTlse** [comment]
Hi, 

anyone can help me figure out what I have to keep in the conflict arisen in package-lock.json file?

Arno

**Comment by stronnag** [comment]
Does not build on case-sensitive operating systems
```
Error: File not found with singular glob: /t/configurators/inav-new_wp/js/safehome.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/t/configurators/inav-new_wp/node_modules/glob-stream/readable.js:84:17)
```

Please make consistent.

**Comment by stronnag** [comment]
Once I work around the case issue, it builds, runs, looks good.

I've found at least one small issue; rather than add any others (if any) piecemeal, I'll post a consolidated report later.

**Comment by stronnag** [comment]
Some initial findings. Note that I'm looking for things that I know are hard, so this is **not** a 'must fix' list. This enhancement is so much better than the extant configurator MP it would be more than OK to publish this with a list of known limitations (IMO).

- [ ] Deleting a JUMP target creates an indeterminate result, particularly for this sample mission.
#### About to delete WP3 (jump target for WP7)
Screenshot-20210415132948-474x454
#### What happened? Why the tower?
Screenshot-20210415133007-615x522
#### Answer. It's the SET_POI point .... maybe we should not delete jump tagets?
Screenshot-20210415135821-854x649
- [ ] No (obvious) way to edit /delete non-geospatial points (SET_HEAD, SET_POI).
- [ ] No (obvious) way to edit points with the same coordinates (in the image WP7 (not visible) is deliberately coincident with WP24 (WP8 is the SET_POI which is (a) not shown and (b) can't be edited)).
image
- [ ] `POSHOLD_TIME` points are wrongly stored as `PH_TIME`. This is non-compliant with the [wiki 'specification'](https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages) and [community xsd]( https://github.com/stronnag/mwptools/blob/master/samples/mw-mission.xsd) and breaks compatibility / interoperability with other tools (ezgui, drone-helper, mwp).
- [ ] trivia. Inconsistent numbering of WPs. Whether one shows mission file numbering (as mwp) or only geo points (as here, almost), be consistent. There is no WP2 (it's the POI). Other non-visited points (SET_POI, JUMP) do not cause a gap in the numbering. 
Screenshot-20210415134147-536x485
 
And to reiterate, these are all "hard to get right / consistent" things. In general it's a great improvement for the configurator.

**Comment by avsaase** [comment]
This is very nice. Really, awesome work Arno! One thing to add to stronnag's comments is that the text along the dashed pink lines is very hard to read. Making the text a little bit bigger should be sufficient.

image

**Comment by DzikuVx** [comment]
So @ArnoTlse which one should be merged? This one or the #1173 
I assume this one, so please close #1173  and then let's resolve conflicts and merge if you think it's ready to be merged :)

**Comment by ArnoTlse** [comment]
> So @ArnoTlse which one should be merged? This one or the #1173
> I assume this one, so please close #1173 and then let's resolve conflicts and merge if you think it's ready to be merged :)

Hi,

I have closed the PR #1173 as it is not valid anymore indeed. This PR #1231 is the one to keep.

Arno

**Comment by ArnoTlse** [comment]
> Does not build on case-sensitive operating systems
> 
> ```
> Error: File not found with singular glob: /t/configurators/inav-new_wp/js/safehome.js (if this was purposeful, use `allowEmpty` option)
>     at Glob.<anonymous> (/t/configurators/inav-new_wp/node_modules/glob-stream/readable.js:84:17)
> ```
> 
> Please make consistent.

Hi @stronnag,

I'm not familiar with blob. I guess it is a compiler stuff? What can be the meaning of non sensitive error in safehome? Is there a character forbidden or a way of declaring something that can trigger such blob issue?

Arno

**Comment by stronnag** [comment]
> > Does not build on case-sensitive operating systems
> > ```
> > Error: File not found with singular glob: /t/configurators/inav-new_wp/js/safehome.js (if this was purposeful, use `allowEmpty` option)
> >     at Glob.<anonymous> (/t/configurators/inav-new_wp/node_modules/glob-stream/readable.js:84:17)
> > ```
> > 
> > 
> > Please make consistent.
> 
> Hi @stronnag,
> 
> I'm not familiar with blob. I guess it is a compiler stuff? What can be the meaning of non sensitive error in safehome? Is there a character forbidden or a way of declaring something that can trigger such blob issue?
> 
> Arno

The file in the repo is called `safeHome.js`, elsewhere ( in `gulpfile.js`) it is referred to as `safehome.js`; note the difference in capitalisation, 'h' v. 'H'. On a case-sensitive file system (i.e. not Windows, so Linux, FreeBSD, MacOS?), the build fails because the names are different. For Windows it does not matter.

Either rename the file in the repo or change the reference in `gulpfile.js` to have consistent capitalisation. Then we can build it in any OS.

**Comment by ArnoTlse** [comment]
> Some initial findings. Note that I'm looking for things that I know are hard, so this is **not** a 'must fix' list. This enhancement is so much better than the extant configurator MP it would be more than OK to publish this with a list of known limitations (IMO).
> 
> * [ ]  Deleting a JUMP target creates an indeterminate result, particularly for this sample mission.
> 
> #### About to delete WP3 (jump target for WP7)
> Screenshot-20210415132948-474x454
> 
> #### What happened? Why the tower?
> Screenshot-20210415133007-615x522
> 
> #### Answer. It's the SET_POI point .... maybe we should not delete jump tagets?
> Screenshot-20210415135821-854x649
> 
> * [ ]  No (obvious) way to edit /delete non-geospatial points (SET_HEAD, SET_POI).
> * [ ]  No (obvious) way to edit points with the same coordinates (in the image WP7 (not visible) is deliberately coincident with WP24 (WP8 is the SET_POI which is (a) not shown and (b) can't be edited)).
>   image
> * [ ]  `POSHOLD_TIME` points are wrongly stored as `PH_TIME`. This is non-compliant with the [wiki 'specification'](https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages) and [community xsd](https://github.com/stronnag/mwptools/blob/master/samples/mw-mission.xsd) and breaks compatibility / interoperability with other tools (ezgui, drone-helper, mwp).
> * [ ]  trivia. Inconsistent numbering of WPs. Whether one shows mission file numbering (as mwp) or only geo points (as here, almost), be consistent. There is no WP2 (it's the POI). Other non-visited points (SET_POI, JUMP) do not cause a gap in the numbering.
>   Screenshot-20210415134147-536x485
> * [ ]  It is possible to edit the JUMP target to be the (hidden) WP2 (the SET_POI). This should not be permitted.
> 
> And to reiterate, these are all "hard to get right / consistent" things. In general it's a great improvement for the configurator.
> 
> Not tested with a flight controller, as it needs to be re-based to 3.0.

Thanks a lot for your feedback and your time to test it.

I'll take a look at the Set POI removal for the WP numbering, and the PH_TIME modification for consistency. I think it can be done quite rapidly.

@avsaase, thanks also. I'll also increase the size of the text as requested.

Arno

**Comment by ArnoTlse** [comment]
> This is very nice. Really, awesome work Arno! One thing to add to stronnag's comments is that the text along the dashed pink lines is very hard to read. Making the text a little bit bigger should be sufficient.
> 
> image

Hi @avsaase,

Just to check, I think the snapshot is related to the previous PR? Normally you shouldn't have this interface in the mission planner menu bar.

Arno

**Comment by ArnoTlse** [comment]
> > > Does not build on case-sensitive operating systems
> > > ```
> > > Error: File not found with singular glob: /t/configurators/inav-new_wp/js/safehome.js (if this was purposeful, use `allowEmpty` option)
> > >     at Glob.<anonymous> (/t/configurators/inav-new_wp/node_modules/glob-stream/readable.js:84:17)
> > > ```
> > > 
> > > 
> > > Please make consistent.
> > 
> > 
> > Hi @stronnag,
> > I'm not familiar with blob. I guess it is a compiler stuff? What can be the meaning of non sensitive error in safehome? Is there a character forbidden or a way of declaring something that can trigger such blob issue?
> > Arno
> 
> The file in the repo is called `safeHome.js`, elsewhere ( in `gulpfile.js`) it is referred to as `safehome.js`; note the difference in capitalisation, 'h' v. 'H'. On a case-sensitive file system (i.e. not Windows, so Linux, FreeBSD, MacOS?), the build fails because the names are different. For Windows it does not matter.
> 
> Either rename the file in the repo or change the reference in `gulpfile.js` to have consistent capitalisation. Then we can build it in any OS.

OK thanks for the clarification. I'll correct it also.

Arno

**Comment by ArnoTlse** [comment]
Hi, 

I have commited the quickest corrections so far. 
I try to have a look for this WE to remove POI in the numbering and avoid user to delete a jump that can redirect to a POI.

Arno

**Comment by stronnag** [comment]
Hi Arno,

I noticed another case-dependent issue. Took an age for my old, tired eyes to spot the difference (after all, it's only a 1 bit error).
in the code (various css) : ` background-image: url(../images/icons/cf_icon_MP_loadfromEprom_grey.svg);`
in the file system `images/icons/cf_icon_MP_loadFromEprom_grey.svg`

The 'F' is capital in the file system and lower-case ('f') in the code. Please change whichever is easiest.

**Comment by ArnoTlse** [comment]
> Hi Arno,
> 
> I noticed another case-dependent issue. Took an age for my old, tired eyes to spot the difference (after all, it's only a 1 bit error).
> in the code (various css) : ` background-image: url(../images/icons/cf_icon_MP_loadfromEprom_grey.svg);`
> in the file system `images/icons/cf_icon_MP_loadFromEprom_grey.svg`
> 
> The 'F' is capital in the file system and lower-case ('f') in the code. Please change whichever is easiest.
> 
> * The affected CSS file is `src/css/tabs/mission_planer.css` (the others are generated build/dist files).

Hi @stronnag ,

Thanks for the notification. I have commited the correction on the mision_planner.css file.

I have also added some Alerts and Confirmations on the removal of a WP known as JUMP target first and also for WP which contains Non-Geo options. For this last one, Confirming the removal will remove also the Non-Geo options attached to the WP. It was'nt the case so far.

Case : Removal of a Target JUMP 

image

Case : Removal of a WP with Non-Geo options : 

image


Arno

**Comment by stronnag** [comment]
Hi Arno,

Good progress.

btw, It looks like the safehome.js / safeHome.js change didn't make it to github (maybe Windows didn't see the change as it's not case-sensitive?).

**Comment by ArnoTlse** [comment]
I have checked. You're right. Github has not taken into account the change of the File name. I try to find out how to take it into account through Github. Otherwise, I will change the call in Gulpfile, but I found convenient to keep filename between Safehome and SafehomeCollection consistent.

Arno

Arno

**Comment by ArnoTlse** [comment]
I have found a way. Normally, It should be better now.

Arno

**Comment by stronnag** [comment]
> I have found a way. Normally, It should be better now.
> 
> Arno

Well done, building here without extra hacks :)

**Comment by stronnag** [comment]
Hi Arno,

I noticed a small regression. The wrong file name was changed in 188399d7d99c5938c092785a12080fccec5080ae / `src/css/tabs/mission_planer.css`, so now the load file icon is missing as well.
Screenshot-20210416215853-357x141

**Comment by Jetrell** [comment]
@ArnoTlse I must say that this looks great. Well done! 
Thanks too @stronnag for your expertise.

**Comment by stronnag** [comment]
Hi Arno,

Here's a UX issue you might want to look at. 
The user cannot edit / move / delete a POI once it has been created and the mission then edited. I hope the video makes the problem clear, it's easier to show a video than try and write a description. Annotations, no sound.

https://user-images.githubusercontent.com/158229/115108347-e5c0d580-9f67-11eb-8bd8-38f943ed3c4e.mp4

The SET_POI is a geographic point that the user should be able to edit / modify / delete. It just does not appear on the path.

Hope the video makes it clear.

**Comment by ArnoTlse** [comment]
> Hi Arno,
> 
> Here's a UX issue you might want to look at.
> The user cannot edit / move / delete a POI once it has been created and the mission then edited. I hope the video makes the problem clear, it's easier to show a video than try and write a description. Annotations, no sound.
> 
>  set_poi.mp4 
> The SET_POI is a geographic point that the user should be able to edit / modify / delete. It just does not appear on the path.
> 
> Hope the video makes it clear.

Hi Stronnag,

Thanks for the video. I look at this issue.
The latest commit pushed corrects normally : 
- issue on the icon for FC, i.e another Sensitive-Case inconsistency.
- Add a message to warn user that he can't assign a JUMP to a POI. This is a small patch waiting for a deep dive in the POI numbering. It will take more time than expected.


Arno

**Comment by stronnag** [comment]
Just had at look at the last commits.
It keeps improving .... 
I really like the different coloured path for the POI/HEAD part. Very nice touch.

**Comment by ArnoTlse** [comment]
Unfortunately, I'm not able to reproduce your case. I don't know what can happen. Is it something repeatable at each time ?
I have followed and repeated several time the same procedure as you have done, but the POI icon is still there on my side, either with or without the FC connected.

**Comment by stronnag** [comment]
> Unfortunately, I'm not able to reproduce your case. I don't know what can happen. Is it something repeatable at each time ?
> I have followed and repeated several time the same procedure as you have done, but the POI icon is still there on my side, either with or without the FC connected.

100% repeatable. Same if I load a mission with SET_POI, the POI is not displayed.

**Comment by ArnoTlse** [comment]
> > Unfortunately, I'm not able to reproduce your case. I don't know what can happen. Is it something repeatable at each time ?
> > I have followed and repeated several time the same procedure as you have done, but the POI icon is still there on my side, either with or without the FC connected.
> 
> 100% repeatable. Same if I load a mission with SET_POI, the POI is not displayed.

Ok., thanks. 
So if you have the issue also just by loading a mission with a SET_POI, maybe it could be a Non-Sensitive Case issue again, I guess. Because on my side, loading a mission with POIs works; the POIs are displayed. I will make a check if there is not again a pb of sensitive case on the filename of the icon.

**Comment by stronnag** [comment]
I just tested in a Win10 VM. The problem does not exist there, so it probably is a case issue.
I'll have a look and see if I can identify the file.

**Comment by ArnoTlse** [comment]
I find it. Sensitive issue indeed.
I'll commit the correction + another one on the lines which not been draggable.

**Comment by stronnag** [comment]
> I find it. Sensitive issue indeed.
> I'll commit the correction + another one on the lines which not been draggable.

Perfect. And I can no longer drag line segments away from the points. Excellent.
Must be getting very close to merge time?

**Comment by ArnoTlse** [comment]
I find a last bug I have just corrected. When I add a Non-Geo options and when I move then the next WP, the WP ended to disappear and the line was frozen. 
I have made a small correction. Seems to correct the issue now.

If you think that this last version could be merged, it's fine for me also.

Arno

**Comment by ArnoTlse** [comment]
Arf, I find another issue. When I save (either to FC or to EPROM), moving a WP make some unwanted behavior. 
But if you save it and then reload it, it works well.
I do not remember having such issue before ; maybe a coutereffect of a correction. I'll check it.

Arno

**Comment by stronnag** [comment]
> Arf, I find another issue. When I save (either to FC or to EPROM), moving a WP make some unwanted behavior.
> But if you save it and then reload it, it works well.
> I do not remember having such issue before ; maybe a coutereffect of a correction. I'll check it.
> 
> Arno

Once you're ready, you need to fix the merge conflicts. They are pretty trivial. I have a local merged with 3.0.
* `package-lock.json` : just keep the HEAD stuff
* `_locales/en/messages.json` : Keep both HEAD and your branch.

We can then deal with any other bugs / omissions through the normal Issue / PR process.

**Comment by stronnag** [comment]
One more small things (sorry, always one more ....). For JUMP, `p2 = -1` is valid (meaning repeat until pilot disables WP mode). Currently it is treated as an illegal value and set to 0. Of course, with JUMP `p2=-1`, the distance is now indeterminate.

**Comment by ArnoTlse** [comment]
I have commited the 3 corrections : 
- one to enable JUMP P2 = -1 + text on the line on that case
- one on issue after Saving to FC & EProm
- one on : selected WP icon was not in red (=selected) once we had a new non-Geo options

Thanks for the feedback; I take the point for the distance computation. I'll integrate it in a future PR with Mission Animation surely as I will have similar thinking about how to loop over Jump.

For mission File upload, I'll also have a look in a futur PR. Normally, there is a IF statement on the MWP tag. So if no info in MWP tag, I'll normally use the first WP coordinate to center the map view. I'll investigate it to make your case working.

Arno

**Comment by stronnag** [comment]
Arno,

Last commit set is looking excellent. I agree, you should get this merged and look at the trivial things later. This will meet the aspirations of most users.

**Comment by ArnoTlse** [comment]
I have found the issue on the last enclosed mission, not loading properly (=empty map without WP). I have corrected the issue.

I change the conflicted files as advised.

Arno

**Comment by stronnag** [comment]
@DzikuVx  Paweł, please merge this magnificent PR

**Comment by ArnoTlse** [comment]
Thanks for all your valuable support Stronnag for this new version of the MP. I have learned a lot thanks to you.
I have updated the ToDo list in #1181 with the topics not yet answered by this first Merge.

Arno

**Comment by DzikuVx** [comment]
Will do!

sob., 17 kwi 2021, 20:52 użytkownik Jonathan Hudson <
***@***.***> napisał:

**Comment by Jetrell** [comment]
@ArnoTlse I recently used this new MP. And I'm impressed with its layout :+1: 

Without criticism.  Can I make a couple of suggestions concerning it.

Presently when a safehome is selected under the manager. Its displayed with a dotted line around it. Adjusted by the Radius tab.

Safehome radius

Being that its a safehome location. My first thought, was the dotted line is  `safehome_max_distance`. Which may be more useful when setting the safehome boundary limit from a known arming location.
What actually does the Radius tab do?

The other is the `Save Eeprom Safehome`. At present a selected safehome is saved to the FC, but is lost when its powered down.
I can't get it to save through this button. It has to be done through the CLI.

What is your view on these idea's?   

Thanks

**Comment by ArnoTlse** [comment]
> @ArnoTlse I recently used this new MP. And I'm impressed with its layout 👍
> 
> Without criticism. Can I make a couple of suggestions concerning it.
> 
> Presently when a safehome is selected under the manager. Its displayed with a dotted line around it. Adjusted by the Radius tab.
> 
> Safehome radius
> 
> Being that its a safehome location. My first thought, was the dotted line is `safehome_max_distance`. Which may be more useful when setting the safehome boundary limit from a known arming location.
> What actually does the Radius tab do?
> 
> The other is the `Save Eeprom Safehome`. At present a selected safehome is saved to the FC, but is lost when its powered down.
> I can't get it to save through this button. It has to be done through the CLI.
> 
> What is your view on these idea's?
> 
> Thanks

Hi @Jetrell,

thanks a lot.

I have in mind at first to plot 2 dotted circle : one for the safehome max distance (200m) and one for a Safe Range distance (50m) for landing as mentionned in this [page](https://github.com/iNavFlight/inav/blob/master/docs/Safehomes.md).
Then, I though it was more convenient to let people to decide which radius they want to plot on the Safehome by adding a Radius Tab in the default settings menu. So by default, it is set to 50m radius, but it can be changed if you click in the settings menu of the MP.
Unfortunately, I have found that when you save the settings, it is not updated straight away the radius on the map. You need to re-click on the House (=Safehome) icon or reload from FC. I will take a look to enable update of the radius once the settings is saved.


On the second point, I reproduce the issue. Strange, because I'm sure I have been able to save it to EPROM (by switching off then on the quad). I'll take a look to enable the saving in the EPROM.

Arno

**Comment by Jetrell** [comment]
@ArnoTlse The two dotted circles, with user selection sounds good, :+1: 
I had noticed that it didn't update the radius change straight away also.

**Comment by Jetrell** [comment]
@ArnoTlse I have a question regarding the operation of Safehome in the mission planner. I ask because I'm not totally sure how this feature in this new mission planner works in its fullness.

I ran some Waypoint flights yesterday, with a Multirotor and a Fixedwing.
When I plotted the mission. I saved the Safehome location to the eeprom and via the CLI.   I then save the mission to the FC eeprom for use.

It ran the missions.... But when it came to the last waypoint and RTH. They did not fly to the safehome location. Instead they would loiter at the arming location.

I know Safehome is working correctly. Because I tested it with both the MR and FW with a failsafe test. And they both loitered at the Safehome location.

The latest Safehome PR that was merged only a week ago, now has two variables. One for the Safehome and the other for the Armed location. This way the OSD telemetry is shown from the arming location and not the Safehome, until an RTH or FS occurs. Only then is the Safehome location used by the Nav system and the OSD telemetry.

Could there be a conflict between the features? 
https://github.com/iNavFlight/inav/commit/852ef27759a5da7d47d56fb54b67c2ed015d70e5

Thanks

Capture

**Comment by stronnag** [comment]
If there is an issue here (and a CLI dump and BBL would be helpful); then it is a firmware issue not a configurator issue. The configurator just saves the geospatial locations of the sahehomes, it does not influence how the firmware handles their usage.

**Comment by Jetrell** [comment]
@stronnag   
I have `Diff All` files, but don't have loggers in any of my test rigs.
The reason I asked about it here. Is because I've never used Safehome with a Waypoint mission before. And wanted know if the way I expected Safehome to work with this MP is correct? 

> 
> 
> If there is an issue here, then it is a firmware issue not a configurator issue. 

That being the case. I'm likely the only one that has tested Safehome V2 in a Waypoint mission from its merged. 

Your input on the matter would be appreciated @tonyyng

**Comment by stronnag** [comment]
It's also the case that RTH/FS RTH and mission RTH are currently handled separately in the firmware ....

**Comment by tonyyng** [comment]
I think I see the problem.  When the mission switches to RTH (`NAV_WP_ACTION_RTH`) in `navOnEnteringState_NAV_STATE_WAYPOINT_PRE_ACTION`, the logic to replace home with safehome needs to be invoked.

@Jetrell Just to confirm, you used `safehome_usage_mode=RTH` in your flight, correct?  If it was `RTH_FS`, the mission RTH should go back to the arming point.

@stronnag Can I make this fix in my previous branch and pull request (https://github.com/iNavFlight/inav/pull/6655) or do I need to create a new branch and pull request?

**Comment by stronnag** [comment]
@tonyyng  Please make a new PR from current `master`. That will also save you any of `rebasing`.

**Comment by Jetrell** [comment]
> 
> 
> I think I see the problem. When the mission switches to RTH (`NAV_WP_ACTION_RTH`) in `navOnEnteringState_NAV_STATE_WAYPOINT_PRE_ACTION`, the logic to replace home with safehome needs to be invoked.
> 
> @Jetrell Just to confirm, you used `safehome_usage_mode=RTH` in your flight, correct? If it was `RTH_FS`, the mission RTH should go back to the arming point.
> 
@tonyyng I had `safehome_usage_mode = RTH_FS` in with both quad and plane.

I've been using @stronnag builds for testing. But they are built after a merge. @tonyyng my test plane will require target MATEKF411_SFTSR2

Thanks

**Pull request merged**
