### PR TITLE
Update to latest NW Builder

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by DzikuVx** [comment]
Blocked by https://github.com/nwutils/nw-builder/issues/1002

**Comment by stronnag** [comment]
Hilariously broken. Or maybe I've just imbibed too much seasonal wine. Let me try and build the **linux** version.
```
$ gulp release --platform linux64
[17:50:43] Using gulpfile /t/configurators/inav-configurator/gulpfile.js
[17:50:43] Starting 'release'...
[17:50:43] Starting 'apps'...
[17:50:43] Starting 'dist'...
[17:50:43] Starting 'clean'...
[17:50:43] Finished 'clean' after 88 ms
[17:50:43] Starting 'dist-build'...
[17:50:43] Starting 'build'...
[17:50:43] Starting 'build-all-css'...
[17:50:43] Starting 'build-all-js'...
[17:50:43] Starting 'build-css'...
[17:50:43] Starting 'build-receiver-css'...
[17:50:43] Starting 'build-js'...
[17:50:43] Starting 'build-receiver-js'...
[17:50:43] Starting 'build-debug-trace-js'...
[17:50:43] Starting 'build-hex-parser-js'...
[17:50:43] Finished 'build-debug-trace-js' after 132 ms
[17:50:43] Finished 'build-hex-parser-js' after 132 ms
[17:50:43] Finished 'build-receiver-css' after 138 ms
[17:50:44] Finished 'build-css' after 150 ms
[17:50:44] Finished 'build-all-css' after 151 ms
[17:50:44] Finished 'build-receiver-js' after 171 ms
[17:50:44] Finished 'build-js' after 322 ms
[17:50:44] Finished 'build-all-js' after 323 ms
[17:50:44] Finished 'build' after 324 ms
[17:50:44] Starting '<anonymous>'...
[17:50:44] Finished '<anonymous>' after 259 ms
[17:50:44] Finished 'dist-build' after 583 ms
[17:50:44] Finished 'dist' after 672 ms
[17:50:44] Starting '<anonymous>'...
 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% | ETA: 0s | 134549453/134549453
Renaming EXE failed or unable to modify EXE. If it's the latter, ensure WINE is installed or build your application Windows platform

```

**Comment by DzikuVx** [comment]
I think it's actually broken in 2 places now:
1. Windows changed API for working with icons (nw-build 3.8.4 now also do not work in windows)
2. `nw-build` fails to detect Windows

As @erstec was able to build Win on MacOS, it seems to be windows related

**Comment by stronnag** [comment]
With master / 7.0.1 I can build any platform on linux. With this PR, I can't build linux on linux ...

**Comment by DzikuVx** [comment]
Yup, at the moment it's completely broken, waiting for any help in https://github.com/nwutils/nw-builder/issues/1002

**Comment by DzikuVx** [comment]
replaced with #1961

**Pull request closed without merging**
