### PR TITLE
Arntlse waypoints mp

### PR DESCRIPTION
**Pull request by ArnoTlse**
Hi,

I have made some evolution on the mission planner tab (see [#1154 ](https://github.com/iNavFlight/inav-configurator/issues/1154)).

**It has not been yet validated and checked in flight, just on desktop with my quad plugged in Inav**, so use it at your own risks while there is no validation by someone expert in Inav coding. I have launched this PR if someone wants and can review my code and see if I have not done something wrong as I am new in Inav coding.

- [x] Save/load mission to File works (desktop check, not in flight)
- [x] Save/load mission to FC works (desktop check, not in flight)
- [x] Save/load from Eprom : Error => I need some help to understand this part

Do not hesitate if you have any question

regards

Arno

### CODE REVIEW

**Comment by DzikuVx** [comment]
I will try to review this in the next few days

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@ArnoTlse good job, but please fix intendations and try to cleanup the code a little.

The reason that EEPROM is not saving is that the mission is not valid. The last waypoint has to have flag set to `NAV_WP_FLAG_LAST` `165`. Right now, mission saves to RAM but it would even not engage since it lacks the last waypoint flag

**Comment by ArnoTlse** [comment]
> @ArnoTlse good job, but please fix intendations and try to cleanup the code a little.
> 
> The reason that EEPROM is not saving is that the mission is not valid. The last waypoint has to have flag set to `NAV_WP_FLAG_LAST` `165`. Right now, mission saves to RAM but it would even not engage since it lacks the last waypoint flag

Hi @DzikuVx ,

Thanks a lot for review and advise.
I guess indentation with only spaces is a common rule to have in every Inav files? I will look after tabulation indentation to change them in spaces and tidy up the code (I have seen some console.log remaining, arghh).
I'll take also a look at that "NAV_WP_FLAG_LAST" = 165, thank you. As I have integrated RTH in the Waypoint tabs and not in the general tab, I have maybe miss that part.

Regards

Arno

**Comment by ArnoTlse** [comment]
Hi,

I have changed all tabulation in spaces. Thus, normally, it should be fine now (hope so).
I have resolved the issue on Eprom saving&loading thanks to your advise @DzikuVx. It works now on desktop tests. Once I manage to find why my magnetometer/GPS isn't working anymore on my quad, I hope I can test it in flight soon.
I have also removed the modification I was doing also on the iconification of the buttons to save spaces; I think I will include it in a future separated PR with "insert WP between existing one" and "WP template path".

Arno

**Comment by ArnoTlse** [comment]
Hi,

I see that package-lock.json is conflicting. I am not used to this, what part should I keep in the resolving ? 

Regards
Arno

**Comment by stronnag** [comment]
Very impressive. I tested it with one of the mwp test "pathologically difficult" mission files.  There are a couple of omissions / specification non-compliance you may still be working on. Attached is the original file and the result:

* `SET_HEAD` is omitted
* `POSHOLD_TIME` is read correctly, but written as ` PH_TIME`, a spec non-compliance and breaks inter-operability with other tools.


[mission-eg.tar.gz](https://github.com/iNavFlight/inav-configurator/files/6067139/mission-eg.tar.gz)

**Comment by ArnoTlse** [comment]
> Very impressive. I tested it with one of the mwp test "pathologically difficult" mission files. There are a couple of omissions / specification non-compliance you may still be working on. Attached is the original file and the result:
> 
> * `SET_HEAD` is omitted
> * `POSHOLD_TIME` is read correctly, but written as ` PH_TIME`, a spec non-compliance and breaks inter-operability with other tools.
> 
> [mission-eg.tar.gz](https://github.com/iNavFlight/inav-configurator/files/6067139/mission-eg.tar.gz)

Hi @stronnag ,

thank you for your feedback and the test case. I am digging into it.
Initially in the mission_planer.js, I found this dict:

```
MWNP.WPTYPE = {
    WAYPOINT:     1,
    PH_UNLIM:     2,
    PH_TIME:      3,
    RTH:          4,
    SET_POI:      5,
    JUMP:         6,
    SET_HEAD:     7,
    LAND:         8
};
```

Then, I understand I need to replace PH_TIME by POSHOLD_TIME. I guess it is the same for PH_UNLIM, replaced by POSHOLD_UNLIM, right ?

**Comment by stronnag** [comment]
You do not need to bother about POSHOLD_UNLIM, it's not implemented in inav; the safest thing to to treat it as a normal waypoint.

If you haven't seen it, the canonical protocol description is in the [inav wiki](https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages) and there is a [XSD in the mwptools repo](https://github.com/stronnag/mwptools/blob/master/samples/mw-mission.xsd). 

I have many "corner case" mission examples (used via mwp to test the firmware implementations as they've been implemented), so you need any more examples, or would like new commits testing, please ping me.

Great to see the configuration mission planner getting some love.

**Comment by ArnoTlse** [comment]
Thanks for both link. I have read the first one at the begining, but I think I haven't noticed the difference between what was already in the code and what is on this page for POSHOLD.

Do you think it is better to remove POSHOLD_UNLIM in the dropdown list in Inav Configurator to avoid someone selecting unsused options by INAV or to keep it and to redirect it in the code behind ?

Great. I try to correct my code based on your test example and I ping you when I push the corrected patch.

**Comment by stronnag** [comment]
> Do you think it is better to remove POSHOLD_UNLIM in the dropdown list in Inav Configurator to avoid someone selecting unsused options by INAV or to keep it and to redirect it in the code behind ?

I would not even offer it for inav, it's just confusing to the user. mwp still supports Multiwii, so it's there; if a mission with UNLIM is uploaded to inav, it's converted to WP. The configurator does not need this complexity.

**Comment by DzikuVx** [comment]
@ArnoTlse what is the state of the code? Do you think it's ready or are you still planning to make any changes? Like removal of POSHOLD_UNLIM  like @stronnag suggests?

**Comment by ArnoTlse** [comment]
Hi @DzikuVx, 

I am currently reworking my code on 2 points : 
- modifying the code to convert POSHOLD_UNLIM to waypoint when reading mission file and hiding this WP in the GUI. 
- modifying the code according WP options (JUMP, HEAD, RTH) to enable the users to ADD several options to a WP as the mission case send by @stronnag shows. 

The last one is a bit longer to develop. I have managed to add a table in place of my radio buttons and I am trying to make working all the interactivity around (read existing options, add new or remove). 

Arno

**Comment by stronnag** [comment]
> Hi @DzikuVx,
> 
> I am currently reworking my code on 2 points :
> 
> * modifying the code to convert POSHOLD_UNLIM to waypoint when reading mission file and hiding this WP in the GUI.
> * modifying the code according WP options (JUMP, HEAD, RTH) to enable the users to ADD several options to a WP as the mission case send by @stronnag shows.
> 
> The last one is a bit longer to develop. I have managed to add a table in place of my radio buttons and I am trying to make working all the interactivity around (read existing options, add new or remove).
> 
> Arno

As you're probably discovering, this can rapidly get quite complex in stopping the user doing things that create an invalid mission; deleting jump targets, trying to jump beyond the mission, deleting an intermediate point in a jump so that the end point is indeterminate. Don't be reluctant to tell the user that she can't do something potentially bad (or you're resetting the JUMP target to WP1 because it's now indeterminate); it's better than having the FC refuse to load this mission with much less feedback.
Screenshot-20210306135623-461x226
Lookin forward (in a constructive way) to testing this to break point :-)

**Comment by DzikuVx** [comment]
@ArnoTlse do you have any progress on this? I'd like to merge it as soon as you think it's ready

**Comment by ArnoTlse** [comment]
Hi @DzikuVx ,

I'am still on it. I have chosen also to clean my code by inserting some OOP stuffs. It will ease more what is done.
It is something I am doing also for Safehome in parallel.

Arno

**Comment by ArnoTlse** [comment]
Hi @DzikuVx,

Work is still in progress. The use of OOP stuff by rewritting WP mission is begining to pay back. I am now able to insert WP on the mission planner between 2 existing points as shown on the mission example given by @stronnag. 

image

I'll keep you updated on my progress.

Arno

**Comment by DzikuVx** [comment]
Awesome @ArnoTlse !

**Comment by ArnoTlse** [comment]
Hi, 

Some updates : I have now the ability to add or remove several options(JUMP, RTH, HEAD) for a waypoint :

image

It will answer the need expressed by the use case of Stronnag.

Things still in progress.

Arno

**Comment by ArnoTlse** [comment]
Hi,

Some progress here : 

I have first created an Hide/Show button for Buttons menu, Mission Information, Waypoint edit & Safehome. It will ease the display.

image

image


I have also changed the Waypoint Edit menu by : 

- removing save buttons : all modification are directly saved and map is updated directly.
- moving the remove button at the top of the menu.
- adding an options table to add JUMP/SET_HEAD/RTH options to the Waypoint. You can add new options by clicking on the + button in the table header. You can remove any point by clicking on the x button on the according line.
- disabling some input fields ("greying" field) + alert message pop-up to avoid user to put wrong values 

image

image



I have created a SafeHome button on the map to open the safehome manager; it generates a Table loading the SAFEHOME with the ability to : 

- Enabled the safehome, move it
- Center the safehome to the current center map view (useful when your safehome is located originally in 0,0 coordinate.
- display 50m radius + 200m radius range around the enabled safehome.

Again, the safehome menu is able to be hidden/shown without removing from display the safehome points. By clicking on the X button, it will close the safehome menu and remove Safehome from map display.

image



This is where I stand today in my development.

Arno

**Comment by ArnoTlse** [comment]
Hi @stronnag,

I have a question about floating numbers. I see in your Mission files that LON/LAT are float numbers (0.000000). On my side, I store integer (0). Is it a problem or do I need to output float also ?

image


regards

Arno

**Comment by stronnag** [comment]
> Hi @stronnag,
> 
> I have a question about floating numbers. I see in your Mission files that LON/LAT are float numbers (0.000000). On my side, I store integer (0). Is it a problem or do I need to output float also ?
> 
> image
> 
> regards
> 
> Arno

The (inherited from Multiwii) mission file XML specification requires that the lat,long is floating point. The MSP specification for communication with the FC requires scaled integers. Most Geo APIs (e.g. OpenLayers) require floating point to draw to the map.

How you store them internally is an application design decision; it's just necessary to conform to the external APIs to be  able to inter-operate.

**Comment by stronnag** [comment]
Apologies, I misinterpreted the question initially.

And the new screen shots look great.

**Comment by ArnoTlse** [comment]
OK, thanks @stronnag. 
Yes my concerns was about non geo points. For the others, outputs are floating.

@DzikuVx and @stronnag , I hope to send a new PR soon in the following weeks with :
- new rearranged code using Waypoints Class to deal with non geopoints options
- insertion of Waypoints between existing WP
- Safehome management.

Things are working in non FC connected mode and I am checking/debugging some stuffs still when FC is connected. 
I am quite closed I think. 

I will add range radius on safehome and mission animation play on another future PR. 

Arno

**Comment by ArnoTlse** [comment]
Hi @DzikuVx and @stronnag,

Code works now for FC & non FC connected.
I wonder whether it would be useful to implement a change for EPROM saving, i.e when user clicks on EPROM saving, if nothing as been saved on the FC first, the button performed both actions ?

I am doing some sanity checks and cleaning a bit the code (removing unnecessary console.log), prior to a new PR.

Arno

**Comment by stronnag** [comment]
> Hi @DzikuVx and @stronnag,
> 
> Code works now for FC & non FC connected.
> I wonder whether it would be useful to implement a change for EPROM saving, i.e when user clicks on EPROM saving, if nothing as been saved on the FC first, the button performed both actions ?

I would recommend you do this, it's much more intuitive for the user (also how mwp does it).

**Comment by ArnoTlse** [comment]
> > Hi @DzikuVx and @stronnag,
> > Code works now for FC & non FC connected.
> > I wonder whether it would be useful to implement a change for EPROM saving, i.e when user clicks on EPROM saving, if nothing as been saved on the FC first, the button performed both actions ?
> 
> I would recommend you do this, it's much more intuitive for the user (also how mwp does it).

OK, thanks. I'll update my code in that sense so.

Arno

**Comment by ArnoTlse** [comment]
Hi @stronnag and @DzikuVx, 

I have made a new PR #1231. Unfortunately I haven't pay attention that I was devolpping on a branch different of this one.

Maybe we'll need to close this one and switch to the other one? 

Arno

**Comment by ArnoTlse** [comment]
Close this PR due to a new one here #1231

**Pull request closed without merging**
