### PR TITLE
Dynamic airplane mixer images

### PR DESCRIPTION
**Pull request by MrD-RC**
A video says a million words, so [click this](https://youtu.be/Bzgj4aXjiII). Note the coloured bars on the servo rows and outputs table are just video edits. The mixer colours have not changed. On the last change in the video I forgot to swap the blue and green colours in the servo mixer table, when the stabilised yaw was set to servo 12. But, you can see the numbers all match up.

The video has everything, except for the notice that the mixer is not loaded. So here's a screen shot of that.
image

### CODE REVIEW

**Comment by wx4cb** [comment]
you could do the whole row like in the video, but i think that just the "servo number" on the bottom part of the mixer would be enough

**Comment by MrD-RC** [comment]
image

**Comment by DzikuVx** [comment]
Seems like most problem are caused when on initial state there is no mixer defined at all.

For example

image


This happened when `Refresh mixer` was clicked without any mixer rules

**Comment by MrD-RC** [comment]
Cool, I'll get on that. Seems like the check for the Refresh mixer needs to be more stringent.

**Comment by MrD-RC** [comment]
[Bug fix resolution](https://youtu.be/9uqnM833ybk)

**Pull request merged**
