### PR TITLE
add support for connect over raw tcp socket

### PR DESCRIPTION
**Pull request by cs8425**
As title, we can use chrome's API to connect.
Should be useful for someone use wifi-to-serial transparent bridge.

### CODE REVIEW

**Comment by DzikuVx** [comment]
@cs8425 Interesting. How can I test it? I do own a couple of ESP8266 . Any specific firmware required or generic serial over WiFi bridge will do?

**Comment by cs8425** [comment]
@DzikuVx 
In theory, generic serial over WiFi **transparent** bridge should work,
which can transfer data between serial and tcp link transparently.
I used esp-01 with esp-link firmware.
test with [esp-link v2.2.3](https://github.com/jeelabs/esp-link/releases/tag/v2.2.3)
I had disabled debug log, not test with debug log on.
(web setting page >> Debug log >> off, see: [https://github.com/jeelabs/esp-link/issues/83](https://github.com/jeelabs/esp-link/issues/83) )
And wire FC's UART(with MSP enable) to ESP's TX/RX.

In configurator,
select `Manual Selection`
type `tcp://esp-ip:port` (esp-link default: `tcp://192.168.4.1:2323`)
and click `connect`

**Comment by ramoonas** [comment]
> @DzikuVx
> In theory, any generic serial over WiFi **transparent** bridge,
> which can transfer data between serial and tcp link transparently, should work.
> I used esp-01 with esp-link firmware.
> test with [esp-link v2.2.3](https://github.com/jeelabs/esp-link/releases/tag/v2.2.3)
> I had disabled debug log, not test with debug log on.
> (web setting page >> Debug log >> off, see: [jeelabs/esp-link#83](https://github.com/jeelabs/esp-link/issues/83) )
> And wire FC's UART(with MSP enable) to ESP's TX/RX.
> 
> In configurator,
> select `Manual Selection`
> type `tcp://esp-ip:port` (esp-link default: `tcp://192.168.4.1:2323`)
> and click `connect`

Does this still need testing? I have nodemcu arduino module set up as transparent TCP to serial bridge on one of my models and i know my arduino code works as i have tested telemetry and mission upload and download via mwptools.

**Comment by ramoonas** [comment]
> > @DzikuVx
> > In theory, any generic serial over WiFi **transparent** bridge,
> > which can transfer data between serial and tcp link transparently, should work.
> > I used esp-01 with esp-link firmware.
> > test with [esp-link v2.2.3](https://github.com/jeelabs/esp-link/releases/tag/v2.2.3)
> > I had disabled debug log, not test with debug log on.
> > (web setting page >> Debug log >> off, see: [jeelabs/esp-link#83](https://github.com/jeelabs/esp-link/issues/83) )
> > And wire FC's UART(with MSP enable) to ESP's TX/RX.
> > In configurator,
> > select `Manual Selection`
> > type `tcp://esp-ip:port` (esp-link default: `tcp://192.168.4.1:2323`)
> > and click `connect`
> 
> Does this still need testing? I have nodemcu arduino module set up as transparent TCP to serial bridge on one of my models and i know my arduino code works as i have tested telemetry and mission upload and download via mwptools.

Oh, just now noticed that year is 2017 :)

**Comment by DzikuVx** [comment]
replaced by #1498

**Pull request closed without merging**
