### PR TITLE
SITL: adjusted SITL tab (built-in serial receiver support)

### PR DESCRIPTION
**Pull request by RomanLut**
Accompanying  submit for https://github.com/iNavFlight/inav/pull/9365

NOTE:  SITL executables in resources folder of inav configurator should be updated from inav repository after merging inav PR!

### CODE REVIEW

**Comment by mmosca** [comment]
@RomanLut can you merge the latest master, to fix the conflicts?

**Comment by RomanLut** [comment]
1) Checked "Serial FC proxy" mode in Windows only. 

Other functionality can not be tested because  serial receivers can not be selected in SITL anymore: https://github.com/iNavFlight/inav/issues/9986

2) SITL Executables has to be updated in Configurator package, a least from here: https://github.com/iNavFlight/inav/actions/runs/8024919315
(I think I am not allowed to submit executables in PR)

**Comment by mmosca** [comment]
I can update the SITL binaries based on latest master from iNavFlight/inav#9988.

Can you remove the Ser2TCP binaries in this pr as, as they won't be needed?

@stronnag Any last minute objections on merging this one?

**Comment by stronnag** [comment]
This PR is working correctly with the current SITL, so I have no issues with merging it.
* The Windows currently attached should be removed (as well as all `ser2tcp`)

Additionally the PATHs wlll need to be cleaned up at some time. At the modent it's a bit of mess, as we have `resources/sitl/<OS>` at build time and `resources/app/resources/sitl/<OS>` post install. 

But that can be addressed after merge.

**Pull request merged**
