### PR TITLE
Make it impossible to modify USB VCP serial port assignment in the GUI

### PR DESCRIPTION
**Pull request by DzikuVx**
image

### CODE REVIEW

**Comment by stronnag** [comment]
Perfect, all the other useful cases require premeditated acts in the CLI (and still need MSP). And if the user is obtuse enough to disable VCP MSP via the CLI, they deserve the consequences.

**Comment by stronnag** [comment]
But why even show VCP?

**Comment by DzikuVx** [comment]
Hmm... good question @stronnag maybe this is the way indeed

**Comment by YI-BOYANG** [comment]
image
Haha, this is really a good PR, I also accidentally turned off the USB VCP once, which made me no longer able to connect to the configurator and had to re-burn the firmware.
At that time I thought, why can't you forbid the user to operate the switch of USB VCP like BF configurator? So I refer to the code of the BF configurator and implement this function on the INAV configurator.
In the end, I didn't submit the PR because I wasn't sure if the INAV configurator left the ability for the player to operate the USB VCP, or what else.

**Comment by DzikuVx** [comment]
@YI-BOYANG I think that @stronnag suggestion to remove VCP from this table completely will be a better idea. I will handle that as soon as I find some time

**Pull request merged**
