### PR TITLE
increased timeout for CLI commands

### PR DESCRIPTION
**Pull request by DzikuVx**
As @theArchLadder found and suggested, this would fix iNavFlight/inav#229 and #6 

@oleost give it a try

### CODE REVIEW

**Comment by theArchLadder** [comment]
I think this needs some testing, perhaps 10ms is enough?

Looks like a dump is almost 400 lines long, at 25ms that would take 10 seconds to restore, that sound okay with me, in fact, i think it would be better to be a little slow because then one would have a chance to see if there was any errors with any settings...

**Comment by DzikuVx** [comment]
Let's confirm 25 works then we can go lower. I can try test it next week perhaps

**Comment by theArchLadder** [comment]
I will also try and test this when i have some time over. As you said, there is not guarantee that even 25ms will solve the problem.

**Comment by oleost** [comment]
I just tested and confirm it worked.

**Comment by theArchLadder** [comment]
@oleost Did you only test one time? Did it feel annoyingly slow?

**Comment by oleost** [comment]
No, I have 10s to wait when restoring entire FC when I update. Even if it would take a minute I still have that time to being certain that everything is being restored correctly.

And when just updating a single value I dont even notice its slower.

**Comment by theArchLadder** [comment]
I just did a few tests, 70 lines(settings, aux etc) was changed from the defaults.
3 restores with 5ms delay, 3 (not sure why this one went so well), 44 and 40 wrong lines.
2 restores with 10ms delay, first had 21 lines wrong, second had 28 lines wrong.
2 restores with 20ms delay, 0 and 20 lines wrong. Perhaps 25ms is not good enough?
2 restores with 40ms delay, 0 and 7 lines wrong... Why does the first attempt work but not the second?!
3 restores at 20ms delay with reconnecting between attempts, 0, 0 and 1 (aux) line wrong, dammit.
2 restores at 20ms delay with restarting configurator between attempts, 0 and 9 lines wrong, dammit.
3 restores at 100ms delay, 0 lines wrong three times in a row, yay! Need to do at least 10 test in a row but i'm way to annoyed to do that now, this was boring! I must automate this so i don't go nuts...

**Comment by oleost** [comment]
@theArchLadder Still good results with 100ms delay?

If so maybe @DzikuVx could change to 100ms delay and then get it merged?

**Comment by theArchLadder** [comment]
@oleost I have not done any more testing, it's so boring! Hopefully i will get around to it some day, but feel free to help test it!

**Comment by oleost** [comment]
Tried 5 in a row with 100ms delay. Not a single line wrong.

**Comment by DzikuVx** [comment]
I will test Today too

**Comment by theArchLadder** [comment]
Feels like the proper solution would be some kind of confirmation message from the FC for each setting that has changed... Anyone know how to do something like that?

**Comment by DzikuVx** [comment]
That probably would require a change in MSP protocol implementation and as far as I know, break any compatibilty. But maybe I'm wrong

**Comment by skaman82** [comment]
is this helpful? https://github.com/cleanflight/cleanflight-configurator/pull/354

**Comment by theArchLadder** [comment]
@skaman82 Yes, i think so! Thanks.

@DzikuVx How about adding that extra delay for profile commands?
https://github.com/cleanflight/cleanflight-configurator/pull/354/files

**Comment by theArchLadder** [comment]
Hmm, wait a minute, betaflight dumps all profiles, right? Does cleanflight do that? Maybe it's only useful in that case, because inav doesn't.

**Comment by theArchLadder** [comment]
Done some more testing.
100ms has always worked for me so far.
The code skaman82 linked to did not seem to make it possible to reduce that 100ms.

But i did find something interesting:
When restoring the dump, the CLI prints out everything that gets restored, but when it misses something it does not get printed! This looks to be true for both settings and aux, i'm sure someone clever could use this to get a confirmation after each restored line... Thoughts?

**Comment by oleost** [comment]
Also tried skaman82 code 549166f9bfcf0866ce7077f1c92e51bf917cd785

Modes worked, but still got lost lines.

**Comment by oleost** [comment]
Please merged this? I need to change it manually everytime and I can think of any reason not merging it?

**Pull request merged**
