### PR TITLE
Add icon for vtx power

### PR DESCRIPTION
**Pull request by MrD-RC**
Configurator change for https://github.com/iNavFlight/inav/pull/7355

Adds VTx power icon.

### CODE REVIEW

**Comment by Jetrell** [comment]
Great idea. What do you think of incorporating #1117 as a TYPE 2? And allow the RF power to be displayed in `mW` as well.

**Comment by MrD-RC** [comment]
@Jetrell  Sounds like a good idea to me. But I’m guessing there’s a reason it wasn’t merged in 3.0? That or it was overlooked. But 100% can add an icon. 

@DzikuVx any reason why #1117 didn’t make it? I can’t see any messages on it or https://github.com/iNavFlight/inav/pull/6326 wit issues.

**Comment by DzikuVx** [comment]
@MrD-RC looks like we have a git conflict. Could you please resolve so we can merge?

**Comment by MrD-RC** [comment]
Sure. I’ll fix as soon as I get home.

**Comment by MrD-RC** [comment]
All good now.

**Comment by jonathanoeijoeng** [comment]
> All good now.

how to show vtx power in mW on OSD?

**Pull request merged**
