### PR TITLE
failsafe changes for 1.6

### PR DESCRIPTION
**Pull request by DzikuVx**
Failsafe changes from #134

@digitalentity @oleost please take a look

### CODE REVIEW

**Comment by oleost** [comment]
Looks good.

image

Maybe we could add an small description to "RTH" ?

Espescially what confuses many people are the "throttle value used while landing". Maybe somehow make it clear that its different from RTH.

**Comment by oleost** [comment]
Found a bug.

**Comment by oleost** [comment]
When changing stuff in "configurator" tab it doesnt reconnect after save and reboot, it only gives me "You need to upgrade your firmware before you can use the configuration tab"

It does not happend on chrome version 1.6.2. Im also running latest inav 1.6.1 release.

image

( I can access the configuration tab when reconnect manually )

**Comment by DzikuVx** [comment]
@oleost This is general "reconnect" problem issue, not Failsafe page specific. I will really have to fix how Configurator handles reconnect and solve it once and for all

**Comment by oleost** [comment]
Are you sure? Newer seen that error message before. And it's fine on 1.6.2 release.

**Comment by DzikuVx** [comment]
Will take a look in the evening. Which board were you using?

**Comment by oleost** [comment]
spracingf3, default settings.

**Comment by oleost** [comment]
Never mind. Wrong board.

On airbotf4 I can replicate it.

https://www.youtube.com/watch?v=ztWGW1pkCvI

**Comment by digitalentity** [comment]
@DzikuVx looks good

**Comment by DzikuVx** [comment]
@oleost Just tested reconnect in this tab on AirbotF4 and SPracingF3. In both cases works like expected. Airbot requires some pateince not to click "connect" but both boards gave me 10/10

**Comment by DzikuVx** [comment]
In case of furter reconnect issues create general "reconnect" ticket

**Pull request merged**
