### PR TITLE
Sort modes in to better order 963

### PR DESCRIPTION
**Pull request by MrD-RC**
Sorts the mode order to be more intuitive in Configurator. It groups modes with similiar modes, to make setting and checking the modes easier in Configurator.

The modes are ordered by:
Arm
Flight modes
Nav modes
Flight mode extenders
Navigation
Fixed Wing specific
Multirotor specific
Feedback (buzzer/LEDs)
OSD
Camera
Misc

This is a part fix for issue #963 

Modes, before and after

### CODE REVIEW

**Comment by Jetrell** [comment]
@MrD-RC It would be quicker to find what your after, than before. 
The only one that looks out of place is `Failsafe`. I would expect it to fall under the `Nav mode` category, because it essentially works the same as `Nav RTH`. Unless it would break the existing API's?

**Comment by MrD-RC** [comment]
Totally agree @Jetrell. It will be so much quicker and easier to setup and way easier to visualise your modes setup.

Personally, I see `Failsafe` as a mode purely to use to test the failsafe state, without having to power off your transmitter. I'd always recommend that `NAV RTH` is used instead of `Failsafe` as an actual flight mode. I know they can operate differently, for example RTH land only with failsafe. But for my understanding, that was not the intention of the switch. https://github.com/iNavFlight/inav/wiki/Modes#failsafe But I'm open to suggestions :)

The ordering here only effects the modes page. So anything can really be put anywhere.

**Comment by Jetrell** [comment]
> 
> 
> Totally agree @Jetrell. It will be so much quicker and easier to setup and way easier to visualise your modes setup.
> 
> Personally, I see `Failsafe` as a mode purely to use to test the failsafe state, without having to power off your transmitter. I'd always recommend that `NAV RTH` is used instead of `Failsafe` as an actual flight mode. I know they can operate differently, for example RTH land only with failsafe. 

Not knocking you view on the matter of RTH.
I once used `Nav RTH mode` for return to home. But after testing over the years. I found that using `Failsafe mode` for return to home, was touching all bases with no side effects.

 * It tests if signal loss Failsafe is working. 
 * it can trigger landing mode with multi-rotors. 
 * It can be triggered by a switch to initiate RTH.

**Comment by avsaase** [comment]
@DzikuVx WDYT?

**Comment by DzikuVx** [comment]
Why not. Only one question: what happens if a mode is not configured in the Configurator? Like: FC adds a new mode, where would it display? @MrD-RC

**Pull request merged**
