### PR TITLE
Add more baud rates to msp connection

### PR DESCRIPTION
**Pull request by mmosca**
Is it faster? Is it just a number?

### CODE REVIEW

**Comment by stronnag** [comment]
Shouldn't this match the list in `src/main/io/serial.c` for maximum placebo effect?

**Comment by mmosca** [comment]
> Shouldn't this match the list in `src/main/io/serial.c` for maximum placebo effect?

Easy change. I was picking values from asm-generic/termbits.h in linux. :)

**Comment by stronnag** [comment]
And the final piece would be  the Ports tab, such that

```
# serial
serial 20 32769 921600 115200 0 115200
serial 0 17 230400 115200 0 115200
```
doesn't result in 

image

**Comment by mmosca** [comment]
Should be all ready for maximum placebo effect.

image

**Comment by mmosca** [comment]
- [ ]

**Pull request closed without merging**
