### PR TITLE
Rearrange advanced tuning page

### PR DESCRIPTION
**Pull request by MrD-RC**
The Advanced Tuning page has been reconfigured. It now will show only relevant settings based on the platform. This should make the page simpler to use. **Fixed Wing** and **Multirotor** have their own top sections. Other platforms see both those sections as a fall-back, The bottom section **Generic settings** is visible for all platforms. There is no replication on any views.

FW Advanced Tuning Page

MR Advanced Tuning Screen

I have also updated the code to use the new data-setting method.

NOTES:
- **Max. Alt-hold climb rate [cm/s]** and **Max. navigation climb rate [cm/s]** used to be in the multirotor navigation settings. However, the are relevant to both fixed wing and multirotor, so are now in the generic settings area.
- The **Tail first** RTH setting is no longer visible on the fixed wing platform, for obvious reasons.
- **Position Estimator** may be removed. @DzikuVx , is also of the opinion that it should be CLI only
- Increased **loiter radius** max to allow https://github.com/iNavFlight/inav/pull/6800 to be used.

### CODE REVIEW

**Comment by avsaase** [comment]
This is great! But the values in your screenshot are weird. Does it still read the settings correctly from the FC?

**Comment by MrD-RC** [comment]
They’re just test values. I did a lot of incrementing and decreasing by 1 to test the values are working. One sec...

**Comment by avsaase** [comment]
> They’re just test values. I did a lot of incrementing and decreasing by 1 to test the values are working. One sec...

Okay, no worries.

**Comment by MrD-RC** [comment]
This is fresh flash using the rovers and boats popup preset.

image
image
image
image

Now with all values changed

image
image
image
image

This was useful though, as I saw a small bug with the titles. I'll upload the fix now.

**Comment by rts18** [comment]
@MrD-RC I agree with @DzikuVx,  `Position Estimator` settings rarely get used by anyone and just clutter up the Configurator.

**Comment by MrD-RC** [comment]
@rts18 It's gone.

The generic settings section has been slightly re-arranged due to this, just to balance the columns a little better. __General Navigation Settings__ is now above __Waypoint Navigation Settings__.

**Comment by avsaase** [comment]
Small suggestion, "Advanced Tuning: Generic Settings" could be replaced by just "Generic Settings"

**Comment by MrD-RC** [comment]
Yes, I agree. no need for the repetition there.

**Comment by avsaase** [comment]
Can we merge this? I'd like to add support for https://github.com/iNavFlight/inav/pull/6437, https://github.com/iNavFlight/inav/pull/6179 and https://github.com/iNavFlight/inav/pull/6695.

**Comment by DzikuVx** [comment]
Sure

**Pull request merged**
