### PR TITLE
Add expanded labels for units

### PR DESCRIPTION
**Pull request by MrD-RC**
This PR adds expanded hover labels for units.

image

### CODE REVIEW

**Comment by Jetrell** [comment]
`Pitch to Throttle ratio` is explained as a ratio, therefor it has no unit...  But it appears to be calculable in `uS`?

**Comment by MrD-RC** [comment]
@Jetrell Yes, you're right. It should be in uS. But you've now got me thinking is _Ratio_ the correct term? It multiplies the `pitch2**thr**` value (which is throttle in uS) by the pitch angle. It's a multiplier rather than a ratio surely?

**Comment by Jetrell** [comment]
I think it depends on how the equation is viewed.
In its simplest form. Its how many `uS` of throttle are applied per degree of Pitch offset from a level attitude. 
But due to this value also being constrained by `nav_fw_min_thr` and `nav_fw_max_thr` ... I think a Ratio would encompass all of that better.
Does that seem right?

But, is it P2T ratio or T2P ratio? 

Something I haven't tested. Is the P2T value constrained?
If someone was to entered a value like 50 (5% ). That would give a 50% throttle increase for 10 degrees of pitch... rather extreme.

**Comment by Jetrell** [comment]
I think it depends if its easier for a person to view it as an equation, or an interaction between variables.
In its simplest form. Its how many `uS` of throttle are changed per degree of Pitch offset from a level attitude.
But due to this value also being constrained by `nav_fw_min_thr` and `nav_fw_max_thr` ... I think a Ratio may encompass all of that better.
Does that seem right?

But, is it a Pitch to Throttle ratio (P2T) or a Throttle value changed, as a result of Pitch (T2P)?

Something I haven't tested. Is the P2T value constrained?
If someone was to entered a value like 50 (5% ). That would give a 50% throttle increase for 10 degrees of pitch... rather extreme.

We understand why its in `uS`.. for resolution. But I wonder if it would be easier for the average person to understand.. e.g. a value ratio of 5, being written as 0.5% throttle change to 1 degree of pitch change?

**Pull request merged**
