### PR TITLE
Increase vbat resolution to 10mV

### PR DESCRIPTION
**Pull request by shellixyz**
Battery voltage resolution of 100mV is not enough for me. This patch increases the voltage resolution to 10mV.

- Voltage scaling/calibration resolution is increased 10 fold. Previous calibration value should be multiplied by 10.
- Increased battery voltage min/max/warning thresholds resolution to 10mV

This PR depends on https://github.com/iNavFlight/inav/pull/2668

### CODE REVIEW

**Comment by shellixyz** [comment]
Outdated, do not merge !

**Comment by digitalentity** [comment]
@shellixyz should we close this?

**Comment by shellixyz** [comment]
I should work on it. Most of the work has been done but I need to adapt the code to the last changes in dev. Would be great if it could be merged before 1.9. I will try to get this ready for tomorrow.

**Comment by shellixyz** [comment]
@digitalentity It is now ready to merge.

**Comment by shellixyz** [comment]
@digitalentity If you are merging https://github.com/iNavFlight/inav/pull/2785 let me mirror the changes in this PR before merging.

**Pull request merged**
