### PR TITLE
Mission control WP send/receive fix

### PR DESCRIPTION
**Pull request by breadoven**
Allows single WP missions to be sent and received from Mission Control. This currently isn't possible without false RTH's appearing when loading and locked send buttons when sending.

Also adds send/receive times to log.

### CODE REVIEW

**Comment by breadoven** [comment]
@DzikuVx @stronnag 
I'll merge this unless some reason is given as to why the current method only works with a minimum of 2 WPs ?

**Comment by stronnag** [comment]
Sure. Don't often use configurator for missions; IMO it should allow the upload of a mission with a single RTH WP as a means of "clear the current in memory mission".

**Comment by breadoven** [comment]
> Sure. Don't often use configurator for missions; IMO it should allow the upload of a mission with a single RTH WP as a means of "clear the current in memory mission".

I tried loading a single WP RTH mission. It doesn't clear missions entirely just shows the single WP RTH mission ... as you might expect. Not sure if this is what @ArnoTlse was after in https://github.com/iNavFlight/inav-configurator/issues/1270. I think he was hoping to clear it completely but the only way to do that is to zero the array so it's back to the post flashing state. I guess a single WP RTH mission just does the same as selecting WP mode with an invalid or empty/unloaded mission so equates to a cleared mission in practical terms.

**Comment by stronnag** [comment]
If you use `mwp` or `impload` it works as expected (and as designed, some 6 years). e.g. this valid mission:
```
<?xml version="1.0" encoding="utf-8"?>
<mission>
  <!--mw planner 0.01-->
  <version value="2.3-pre8"></version>
  <mwp save-date="2021-11-01T15:53:15+0000" zoom="14" cx="-4.7021103" cy="54.1384679" generator="mwp (mwptools)"></mwp>
  <missionitem no="1" action="RTH" lat="0.0000000" lon="0.0000000" alt="0" parameter1="0" parameter2="0" parameter3="0"></missionitem>
</mission>

```

**Comment by stronnag** [comment]
I can load the above file into the configurator, I can save it from the configurator to a file (with the same 1 RTH WP). I just can't upload it the FC via the configurator.

**Comment by stronnag** [comment]
Indeed, this PR should be merged.

**Pull request merged**
