### PR TITLE
Port of Betaflight OSD support

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by DzikuVx** [comment]
@digitalentity @martinbudden @oleost @stronnag PR is done
There were quite massive changes in MSP layer so please click through whole configurator.
Besides that, initial OSD support is ready, we will not go further in 1.5 that that

**Comment by digitalentity** [comment]
I don't see any ill effects - everything seems to function properly

**Comment by DzikuVx** [comment]
@jflyper found some minor issues I will investigate

**Comment by digitalentity** [comment]
Found a bug. Non-detected (failing) sensors are flashing red. Probably Configurator is processing sensor status (and updated sensor iconds) from both `MSP_STATUS` and `MSP_SENSOR_STATUS` messages while in 1.5 only `MSP_SENSOR_STAUS` should be used for displaying sensor icons.

**Comment by DzikuVx** [comment]
@digitalentity I will work on it while implementing sensor enabling

**Pull request merged**
