### PR TITLE
Added 3D plane model to setup page

### PR DESCRIPTION
**Pull request by MrD-RC**
Added a 3D plane model, so fixed wing pilots who like tails, don't have to stare at the CleanFlight box any more.

image

Note: I have set the control surface colours to:
- Port = Red
- Starboard = Green
- Elevator = Orange
- Rudder = Blue

The red and green for port/starboard are to match the aeronautical navigation lights, as suggested by @OptimusTi. I will submit a pull to update the mixer images soon. If it's thought that the current colours are better, I can modify this to have the same colours as the current mixer.

_Update_
The mixer models are here https://github.com/iNavFlight/inav-configurator/pull/1288

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]

**Comment by avsaase** [comment]
@DzikuVx why not do this for 3.0? We have the wing model so it would be nice to add the plane model in the same release.

**Comment by MrD-RC** [comment]
@avsaase possibly because of the colour changes on the control surfaces. It would mean that @ted-rcnet 's cool wing model (#1202) would not match. Maybe there's not enough time for that to get updated, if the colours matching is important.

It will be cool once it's in there, whether that's in 3.0 or 3.1. I have other plans too ;)

**Comment by MrD-RC** [comment]
FCB9F0F7-1FD9-4820-8996-D1AD285A88F7

**Comment by MrD-RC** [comment]
If you are thinking of merging, give me a day as I’ve updated the v-tail. I just need to get it formatted in Blender and uploaded. But I have 8 hours of work before I’ll get to do that. I will be working on a rudderless plane too, but I can create a separate PR for that.

**Comment by DzikuVx** [comment]
@MrD-RC I will rather not merge before next week so easy, we should be fine in here

**Comment by MrD-RC** [comment]
All updated. So ready whenever you are happy 👍

**Comment by DzikuVx** [comment]
I'm happy! So will merge to master quite soon

pt., 4 cze 2021, 22:35 użytkownik Darren Lines ***@***.***>
napisał:

**Comment by b14ckyy** [comment]
@DzikuVx it's about time I guess? :D

**Pull request merged**
