### PR TITLE
Add UI units to number inputs

### PR DESCRIPTION
**Pull request by elgansayer**
**What?**
Adds an option to set how the inputs should display on the UI. 

- **Imperial** UI units are imperial
- **OSD** UI units are the same as OSD
- **Metric** UI units are metric
- **None** Do not convert units

inav

**Adding more confirmation elements**

Add `data-unit=` attribute to the input to explain what the input should be. 
              
```
<input type="number" id="launchVelocity" data-unit="cms" data-setting="nav_fw_launch_velocity" data-setting-multiplier="1" step="1" min="1000" max="2000" />
```

Float units are fixed to 2dp or ints are displayed as whole numbers
That's it!

- cm centimetres. Converts to metres for metric or feet for imperial and GA
- cms centimetres/seconds. Converts to MPH for imperial and metric + MPH, Km/h for metric, and Knots for GA
- ms milliseconds. Converts to seconds

**Here is a video of it working**
Click Click Click 
[Watch the video](https://www.youtube.com/watch?v=mdxHMdDKvI4)

### CODE REVIEW

**Comment by DzikuVx** [comment]
@elgansayer please resolve conflicts

**Comment by elgansayer** [comment]
Resolved using the online editor, but there is a missing field that i cant update right now.

**Comment by DzikuVx** [comment]
@elgansayer ping me when ready. Worst case: we will not put this in RC1

**Comment by MrD-RC** [comment]
Just tested the zip from @elgansayer repo, and the change is working. There are a couple of things that could be improved, but this is working on the Advanced Tuning page. Everything is saving and the conversions are working. There is some discrepancy between input imperial/GA measurements and what you see when you next return to the page. But this is unavoidable as there is a conversion going on. The conversions are sound though:

| Function | Imperial | Calculated conversion | FC stored
|----------|----------| -------------------------|-----------|
| Loiter radius | 250 ft | 7620 cm | 7620 cm |
| Emergency landing speed | 10.98 mph | 490.85 cm/s | 491 cm/s |
| Launch Timeout | 6 sec | 6000	ms | 6000 ms |

| Function | Metric | Calculated conversion | FC stored
|----------|----------| -------------------------|-----------|
Loiter radius | 76.2 m | 7620 cm | 7620 cm |
Emergency landing speed | 17.68 km/h | 491.11 cm/s | 491 cm/s |

| Function | GA | Calculated conversion | FC stored
|----------|----------| -------------------------|-----------|
Emergency landing speed | 9.54 kt | 490.78 cm/s | 491 cms

**Comment by elgansayer** [comment]
The new commits look sound and make sense. Good work @darren!

code not run. I don't have a flight controller as I'm away for a week with
only work pc. The code makes sense, I see no issues.

I think 4.1 would be fine

**Comment by DzikuVx** [comment]
I will try to test it over the weekend, it can always hit 4.0 RC2 :)

**Comment by MrD-RC** [comment]
Fixes #1201

**Pull request merged**
