### PR TITLE
CRSF RSSI alarm

### PR DESCRIPTION
**Pull request by avsaase**
Configurator support for https://github.com/iNavFlight/inav/pull/6960.

### CODE REVIEW

**Comment by OptimusTi** [comment]
Is there going to be updated fonts for the new changes?

**Comment by avsaase** [comment]
No, I decided to keep the symbols as they are. I kept going back and forth between having the RSSI and dBm symbol separate and combined, so I thought let's not change it any more for now.

**Comment by OptimusTi** [comment]
Understood. Will spacing remain the same as 2.6 so elements align correctly?

**Comment by avsaase** [comment]
For 3.0 it looks like in https://github.com/iNavFlight/inav/pull/6950#issuecomment-840098629.

**Pull request merged**
