### PR TITLE
adding support for mapproxy #593

### PR DESCRIPTION
**Pull request by tednv**
tested this using my local instances, works just fine. will need to add documentation section for how to setup mapproxy, add a wms layer, and point inav to use it which allows for offline map cache

### CODE REVIEW

**Comment by DzikuVx** [comment]
Perfect, please add documentation so I will test and review as soon as possible

**Comment by tednv** [comment]
don't know of the best way to integrate document into repo, attaching as text file for now so it can be tested since it'll take me a while to get formatting done
[mapproxy setup doc.txt](https://github.com/iNavFlight/inav-configurator/files/2619230/mapproxy.setup.doc.txt)
included OpenStreetMap free wms service and google maps cache config examples, but any mapproxy supported service can be used

**Comment by tednv** [comment]
let me know if I missed anything but that should cover the basic install, I tested on a windows 10 build of configurator from scratch, both examples are working for me

**Comment by tednv** [comment]
also more free USGS map services can be found here, QGIS can be used to preview layers and pick ones for MapProxy source
https://viewer.nationalmap.gov/services/

I'm in the US so I'm more familiar with US ones, but there are similar services worldwide

**Comment by tednv** [comment]
most gov weather agencies also provide wms services, they can be layered with mapproxy
https://mapproxy.org/docs/nightly/configuration_examples.html#merge-multiple-layers
so it is possible to get satellite or topography maps and overlay things like visibility, radar, wind speed, etc on top of them which may also be useful for flying
https://nowcoast.noaa.gov/help/#!section=wms-layer-ids
for industry specific applications usgs (and similar) layers are very good for surveying and prospecting

**Comment by DzikuVx** [comment]
@tednv could you please rebase on current `master` branch?

**Comment by DzikuVx** [comment]
@tednv I have only one remark: please put some basic documentation for to use it. 
Perhaps content of https://github.com/iNavFlight/inav-configurator/files/2619230/mapproxy.setup.doc.txt as a MD file a link to it from Readme.MD so users can easily find what goes where. 
This thing and I suppose we are ready to go with this one

**Comment by tednv** [comment]
this should be ready to go. one thing I noticed is zoom level keeps going back to default, but it does it with built in OpenStreetMap setup too, will add separate issue to check that

**Comment by DzikuVx** [comment]
and merged, thank a lot @tednv

**Pull request merged**
