### PR TITLE
Bump nw.js to v0.77 to support apple silicon macs

### PR DESCRIPTION
**Pull request by mmosca**
Needs more testing, but builds and runs.

I don't have any fc with me at the moment to check all the functionality

### CODE REVIEW

**Comment by stronnag** [comment]
Seems fine on Linux64. All tabs display as expected

**Comment by DzikuVx** [comment]
Yeah, @mmosca see:
https://github.com/iNavFlight/inav-configurator/issues/1943
and 
https://github.com/iNavFlight/inav-configurator/pull/1929

**Comment by mmosca** [comment]
That is why I haven’t merged it yet. But me being able to build it is more important (for me) than be at the moment. 😉

**Comment by DzikuVx** [comment]
replaced with #1961

**Pull request closed without merging**
