### PR TITLE
Add model flying wing 3D

### PR DESCRIPTION
**Pull request by ted-rcnet**
Add model flying wing 3D

FlyingWing-g

### CODE REVIEW

**Comment by ted-rcnet** [comment]
hi,
Yes, my setup is blender 2.78 and plugin export .json Three.js r92
here are the instruction by Thomas Shue's on youtube https://www.youtube.com/watch?v=DIE_vytEG8s

**Comment by MrD-RC** [comment]
@ted-rcnet would you mind sharing your JSON export settings. I've tried the video above, but the r92 is different to what's being show in the video, and I'm not getting anything displayed in the configurator at all.

**Comment by MrD-RC** [comment]
@ted-rcnet would you mind sharing your JSON export settings. I've tried the video above, but the r92 is different to what's being show in the video, and I'm not getting anything displayed in the configurator at all.

**Comment by MrD-RC** [comment]
Actually it looks like blender only wants to export 1 object at a time, which is really helpful. I only have the material for the selected object in the json file. Even selecting all the objects doesn't change this. Why can't Fusion 360 have an export json that works 😢

**Comment by MrD-RC** [comment]
I'm getting closer. Anyone have any idea how I can output the missing objects? I have made them all a child of the main plane object. But still the control surfaces and motor components don't output.

Output by Three.js
image

What it should look like
image

**Comment by OptimusTi** [comment]
if I may suggest using red color on port wing, green on starboard wing and blue on rudder. :)

**Comment by MrD-RC** [comment]
@OptimusTi I've used the colours from the mixer, to keep it consistent. The rudder has no colour, so I went with green. 
image

Red on the left and green on the right makes sense from a navigation point of view; so maybe all the colours should change?

**Comment by MrD-RC** [comment]
By the way, the issue with the export is resolved. You need to combine all objects in to a single mesh with Ctrl + J

**Comment by MrD-RC** [comment]
@OptimusTi 

CC03B1D5-6C5B-4AD8-A5A0-A5AD7713C580

@DzikuVx what are your thoughts on changing the colours to the official port and starboard colours. It should be pretty quick to implement.

**Comment by DzikuVx** [comment]
Let's do it for 3.1 yes

śr., 2 cze 2021, 17:31 użytkownik Darren Lines ***@***.***>
napisał:

**Comment by MrD-RC** [comment]
You're call @DzikuVx 

The PR is here whenever you would like to merge it https://github.com/iNavFlight/inav-configurator/pull/1288
The plane 3D model is here https://github.com/iNavFlight/inav-configurator/pull/1287

**Comment by DzikuVx** [comment]
Awesome @MrD-RC !

**Comment by ted-rcnet** [comment]
Hi,
I'm sorry, I was unavailable
@MrD-RC The model is available in blender format on my repositories various
https://github.com/ted-rcnet/various.git

**Comment by MrD-RC** [comment]
No problem @ted-rcnet. I got there in the end. Just made another one in no time at all 🛩️

**Pull request merged**
