### PR TITLE
Serial gimbal support

### PR DESCRIPTION
**Pull request by mmosca**
Configurator counterpart for iNavFlight/inav#10109

Currently only include the changes to the ports tab.

May eventually add support for the configuration settings.

### CODE REVIEW

**Comment by mmosca** [comment]
While adding the modes, I grouped  some items together to make them easier to spot.

image

**Comment by mmosca** [comment]
This is an example of the setup on the ports tab.
image

In this example, UART6 can be used if headtracker type is set to MSP on the configuration tab and UART4 can be used if type is SERIAL.

**Comment by mmosca** [comment]
Current configuration tab options, subject to change:
image

**Comment by shannonbaker** [comment]
[AUTO] selection of input is not working for Gimbal modes.

**Pull request merged**
