### PR TITLE
Mission planer

### PR DESCRIPTION
**Pull request by Afinogen**
The first version, I accept offers and wishes.
Download and save does not work yet

### CODE REVIEW

**Comment by DzikuVx** [comment]
wow… great beginning!

**Comment by Afinogen** [comment]
Need to fix the css styles

**Comment by DzikuVx** [comment]
@Afinogen is this any usable?

**Comment by Afinogen** [comment]
@DzikuVx I did not understand the question
If it's about styles, then need to make adaptability

**Comment by DzikuVx** [comment]
I mean if i can plan a mission and upload. Basic functionality and all of tha

**Comment by Afinogen** [comment]
@DzikuVx  Yes, it work. Checked in MP for android

**Comment by Afinogen** [comment]
Corrected styles, now looks better

**Comment by digitalentity** [comment]
Seems working. Not perfect, but we'll improve it on the way

**Pull request merged**
